/* TUBAL HUB v4.1 FINAL — Personal OS for Ar-ar Tubal / tubalrr */
'use strict';
const K='tubalhub_v41';
const PRAYER_FALLBACK={Fajr:'4:30 AM',Dhuhr:'12:00 PM',Asr:'3:30 PM',Maghrib:'6:00 PM',Isha:'7:15 PM'};
const state=JSON.parse(localStorage.getItem(K)||'null')||{setup:false,name:'',city:'Davao',currency:'PHP',tasks:[],events:[],finance:{income:0,tx:[],budgets:[{title:'Food',limit:5000,spent:0},{title:'Bills',limit:5000,spent:0},{title:'Padala',limit:3000,spent:0},{title:'Luho',limit:2000,spent:0},{title:'Ipon',limit:5000,spent:0}]},hulugan:[],clients:[],goals:[],habits:[{id:id(),title:'Deep Work',checks:{}}],notes:[],library:[],journals:[],focus:[],prayers:PRAYER_FALLBACK,weather:null,quote:null,holidays:[],api:{},changelog:[]};
const app=document.getElementById('app'), modal=document.getElementById('modalRoot');
let route=location.hash.slice(1)||'home', focusTimer=null, focusState=null, analyticsTab='overview', calendarDate=new Date();
function id(){return Date.now()+Math.random().toString(16).slice(2)}
function save(){localStorage.setItem(K,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function iso(d=new Date()){const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}
function money(n){return new Intl.NumberFormat('en-PH',{style:'currency',currency:state.currency||'PHP',maximumFractionDigits:0}).format(Number(n)||0)}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function days(a,b=iso()){return Math.round((new Date(a)-new Date(b))/86400000)}
function nav(r){route=r;location.hash=r;render()}
function modalBox(title,body,buttons='<button class="btn alt" data-close>Close</button>'){modal.innerHTML='<div class="modal"><div class="modal-box"><div class="head"><h2>'+esc(title)+'</h2><button class="btn alt" data-close>×</button></div>'+body+'<div class="toolbar" style="justify-content:flex-end;margin-top:18px">'+buttons+'</div></div></div>';modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.innerHTML='')}
function layout(title,body){return '<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">TH</div><div><b>TUBAL HUB</b><small>Personal OS · Ar-ar Tubal</small></div></div><nav class="nav"><div class="nav-section">MAIN</div>'+navButton('home','⌂','Dashboard')+navButton('calendar','▦','Calendar')+navButton('tasks','✓','Tasks')+'<div class="nav-section">MONEY & WORK</div>'+navButton('finance','₱','Finance')+navButton('goals','◎','Goals & Habits')+navButton('clients','◫','Client CRM')+'<div class="nav-section">PERSONAL</div>'+navButton('notes','✎','Notes & Vault')+navButton('library','▤','Library')+'<div class="nav-section">INSIGHTS</div>'+navButton('analytics','◒','Analytics')+navButton('weekly','◷','Weekly Review')+navButton('changelog','◇','Changelog')+'<div class="nav-section">QUICK TOOLS</div><button data-cmd><span class="nav-icon">⌘</span>Command Palette<span class="nav-key">Ctrl K</span></button><button data-focus-top><span class="nav-icon">◉</span>Focus Mode</button><button data-export><span class="nav-icon">⇩</span>Export Backup</button><button data-import><span class="nav-icon">⇧</span>Import Backup</button></nav><div class="side-foot">v4.1 · Local-first<br>Free APIs · Taglish only</div></aside><main class="main"><header class="top"><div class="top-left"><button class="mobile-menu" data-menu>☰</button><div><div class="eyebrow">TUBAL HUB v4.1</div><h1>'+esc(title)+'</h1></div></div><div class="date">'+new Intl.DateTimeFormat('fil-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date())+'</div></header><div>'+body+'</div></main><nav class="bottom">'+['home','calendar','tasks','finance','analytics'].map(r=>'<button class="'+(route===r?'active':'')+'" data-route="'+r+'">'+({home:'⌂',calendar:'▦',tasks:'✓',finance:'₱',analytics:'◒'}[r])+'<br>'+r+'</button>').join('')+'</nav></div>'}
function navButton(r,i,t){return '<button class="'+(route===r?'active':'')+'" data-route="'+r+'"><span class="nav-icon">'+i+'</span>'+t+(r==='analytics'?'<span class="new">New</span>':'')+'</button>'}
function section(k,t,b){return '<div class="section-head"><div class="eyebrow">'+k+'</div><h2>'+t+'</h2></div>'+b}
function card(t,b){return '<div class="card"><div class="head"><h3>'+t+'</h3></div>'+b+'</div>'}
function dashboard(){const today=iso(),overdue=state.tasks.filter(x=>!x.done&&x.date<today).length,todayTasks=state.tasks.filter(x=>!x.done&&x.date===today),week=state.tasks.filter(x=>!x.done&&days(x.date)>=0&&days(x.date)<7).length,ren=state.hulugan.filter(x=>days(x.next)<=30&&days(x.next)>=0),score=lifeScore(),ins=insights()[0]||{title:'Tuloy lang',text:'Maliit na progress, malaking tulong.'},upcoming=[...state.events.map(x=>({...x,type:'Event'})),...state.tasks.filter(x=>!x.done).map(x=>({...x,type:'Task'}))].filter(x=>x.date>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5),streak=state.habits.reduce((m,h)=>Math.max(m,habitStreak(h)),0),spent=state.finance.budgets.reduce((a,x)=>a+Number(x.spent||0),0),income=state.finance.income;
return layout('Dashboard','<div class="hero"><div><div class="eyebrow">PERSONAL OS · TODAY</div><h2>Hi, '+esc(state.name)+'. Ayusin natin ang araw.</h2><p>Isang lugar para sa tasks, pera, work, habits at daily closing.</p></div><div class="hero-actions"><button class="btn" data-action="quick">+ Quick Capture</button><button class="btn alt" data-action="closing">Daily Closing</button></div></div>'+
'<div class="kpis"><div class="card kpi">Overdue<strong>'+overdue+'</strong><span class="muted">Needs attention</span></div><div class="card kpi">Today<strong>'+todayTasks.length+'</strong><span class="muted">'+(todayTasks.filter(x=>x.done).length)+' done</span></div><div class="card kpi">This Week<strong>'+week+'</strong><span class="muted">Open tasks</span></div><div class="card kpi">HULUGAN &lt;30d<strong>'+ren.length+'</strong><span class="muted">Due soon</span></div></div>'+
'<div class="grid home-top"><div class="card"><div class="head"><h3>Life Score</h3><span class="pill green">'+score+'/100</span></div><div class="score">'+score+'</div><div class="progress"><i style="width:'+score+'%"></i></div><p class="muted">Tasks · budget · habits · mood</p><button class="btn alt" data-route="analytics">Open Analytics</button></div>'+
'<div class="card"><div class="head"><h3>Quick Actions</h3><span class="muted">One tap</span></div><div class="quick-grid"><button class="btn alt" data-action="addTask">✓ New Task</button><button class="btn alt" data-action="addExpense">₱ Expense</button><button class="btn alt" data-action="addEvent">▦ Event</button><button class="btn alt" data-action="focus">◉ Focus 25m</button></div></div>'+
'<div class="card"><div class="head"><h3>Davao Weather</h3><span class="pill blue">'+(state.weather?'LIVE':'LOCAL')+'</span></div><h2>'+(state.weather?.temperature??32)+'°C</h2><p class="muted">Davao · Open-Meteo</p></div>'+
'<div class="card"><div class="head"><h3>Next Prayer</h3><span class="pill yellow">'+esc(state.city)+'</span></div><h2>'+nextPrayer().name+' · '+nextPrayer().time+'</h2><p class="muted">'+nextPrayer().remaining+' remaining</p></div></div>'+
'<div class="cards">'+card('Today Tasks',todayTasks.slice(0,6).map(taskRow).join('')||'<p class="muted">Wala pang task today. Good time mag-add.</p>')+
card('Upcoming',upcoming.map(x=>'<div class="row"><span><b>'+esc(x.title)+'</b><br><small class="muted">'+esc(x.date)+' · '+x.type+'</small></span><span class="pill '+(x.type==='Event'?'blue':'green')+'">'+x.type+'</span></div>').join('')||'<p class="muted">Walang upcoming.</p>')+'</div>'+
'<div class="cards">'+card('Finance Snapshot','<div class="row"><span>Income</span><b>'+money(income)+'</b></div><div class="row"><span>Envelope gastos</span><b>'+money(spent)+'</b></div><div class="row"><span>Saved this month</span><b>'+money(savedMonth())+'</b></div><button class="btn alt" data-route="finance">Open Finance</button>')+
card('HULUGAN Due Soon',ren.slice(0,4).map(x=>'<div class="row"><span><b>'+esc(x.title)+'</b><br><small class="muted">Buwanang Bayad · '+esc(x.next)+'</small></span><b>'+money(x.monthly)+'</b></div>').join('')||'<p class="muted">Wala ka pang hulugan — ayos!</p>')+'</div>'+
'<div class="cards">'+card('Habits Streak','<div class="score">'+streak+' <small>days</small></div><p class="muted">Pinakamahabang current streak</p><button class="btn alt" data-route="goals">Open Habits</button>')+
card('Insight of the day','<b>'+esc(ins.title)+'</b><p class="muted">'+esc(ins.text)+'</p><button class="btn alt" data-route="analytics">See Insights</button>')+'</div>'+
'<div class="card"><div class="head"><h3>Daily Quote</h3><span class="pill green">Closing</span></div><div class="quote">'+esc(state.quote||'Kahit maliit ang progress, progress pa rin.')+'</div><div class="toolbar"><button class="btn alt" data-action="closing">Gamitin sa Daily Closing</button></div></div>');
}
function taskRow(t){return '<div class="row"><label class="check"><input type="checkbox" data-task="'+t.id+'" '+(t.done?'checked':'')+'><span class="'+(t.done?'done':'')+'">'+esc(t.title)+'</span></label><button class="btn alt" data-focus="'+t.id+'">Focus</button></div>'}
function calendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<div></div>';for(let n=1;n<=last;n++){const d=iso(new Date(y,m,n)),h=state.holidays.find(x=>x.date===d),items=[...state.events.filter(x=>x.date===d),...state.tasks.filter(x=>x.date===d).map(x=>({title:x.title,color:'blue'}))];cells+='<div class="day '+(d===iso()?'today':'')+'"><b>'+n+'</b>'+(h?'<span class="chip orange">🇵🇭 '+esc(h.localName||h.name)+'</span>':'')+items.slice(0,h?4:5).map(x=>'<span class="chip '+(x.color||'blue')+'">'+esc(x.title)+'</span>').join('')+'</div>'}return layout('Calendar',section('YOUR DAYS','Calendar','<div class="toolbar"><button class="btn" data-action="addEvent">+ Add event</button><button class="btn alt" data-action="addTask">+ Task</button><button class="btn alt" data-action="refreshAPIs">↻ Refresh APIs</button></div><div class="prayer-line card" style="padding:12px">🇵🇭 PH Holidays: '+(state.api.holidays?'LIVE/CACHED':'loading')+' · 🕌 Prayer: '+(state.api.prayer?'LIVE/CACHED':'fallback')+'</div><div class="card"><div class="head"><h3>'+new Intl.DateTimeFormat('fil-PH',{month:'long',year:'numeric'}).format(calendarDate)+'</h3><div><button class="btn alt" data-cal="-1">←</button> <button class="btn alt" data-cal="1">→</button></div></div><div class="calendar-wrap"><div class="calendar-grid">'+['Lun','Mar','Miy','Huw','Biy','Sab','Lin'].map(x=>'<div class="weekday">'+x+'</div>').join('')+cells+'</div></div></div>'))}
function tasks(){return layout('Tasks',section('WORK','Tasks','<div class="toolbar"><button class="btn" data-action="addTask">+ Task</button><button class="btn alt" data-action="quick">Quick Capture</button><span class="pill blue">'+state.tasks.filter(x=>x.done).length+' done</span></div><div class="cards">'+card('List',state.tasks.map(taskRow).join('')||'<p class="muted">Wala pa. Add task muna.</p>')+card('Recurring',state.tasks.filter(x=>x.repeat).map(x=>'<div class="row"><span>'+esc(x.title)+'</span><span class="pill green">'+esc(x.repeat)+'</span></div>').join('')||'<p class="muted">Wala pang recurring task.</p>')+'</div><div class="card"><h3>Kanban Flow</h3><div class="kanban">'+['todo','doing','done','blocked'].map(s=>'<div><b>'+s.toUpperCase()+'</b>'+state.tasks.filter(x=>(x.status||'todo')===s).map(x=>'<p>'+esc(x.title)+'</p>').join('')+'</div>').join('')+'</div></div>'))}
function finance(){const spent=state.finance.budgets.reduce((a,b)=>a+Number(b.spent||0),0),rec=state.clients.filter(x=>x.status!=='Paid').reduce((a,x)=>a+Number(x.amount||0),0);return layout('Finance',section('MONEY','Finance','<div class="kpis"><div class="card kpi">Income<strong>'+money(state.finance.income)+'</strong></div><div class="card kpi">Gastos<strong>'+money(spent)+'</strong></div><div class="card kpi">Receivable<strong>'+money(rec)+'</strong></div><div class="card kpi">HULUGAN<strong>'+state.hulugan.length+'</strong></div></div><div class="cards">'+card('Budget Envelopes',state.finance.budgets.map(b=>'<div style="margin:14px 0"><div class="progress-text"><span>'+esc(b.title)+'</span><b>'+money(b.spent)+' / '+money(b.limit)+'</b></div><div class="progress"><i style="width:'+Math.min(100,b.spent/b.limit*100)+'%"></i></div></div>').join(''))+card('HULUGAN Tracker','<button class="btn" data-action="addHULUGAN">+ HULUGAN</button>'+state.hulugan.map(x=>'<div class="row"><span><b>'+esc(x.title)+'</b><br><small class="muted">Buwanang Hulog: '+money(x.monthly)+' · Ilang buwan pa: '+Math.max(0,x.months-x.paid)+'</small></span><span class="pill '+(x.paid>=x.months?'green':'orange')+'">'+(x.paid>=x.months?'Tapos na bayaran!':'Buwanang Bayad')+'</span></div>').join('')+(state.hulugan.length?'':'<p class="muted">Wala ka pang hulugan — ayos!</p>'))+'</div><div class="card"><div class="head"><h3>Forecast Next Month</h3><span class="pill blue">3-month estimate</span></div><h2>'+money(spent*1.03)+'</h2><p class="muted">Tantyang gastos base sa current envelopes.</p><button class="btn alt" data-action="addIncome">+ Income</button> <button class="btn alt" data-action="addExpense">+ Expense</button></div>'))}
function goals(){return layout('Goals & Habits',section('GROW','Goals + Habits','<div class="toolbar"><button class="btn" data-action="addGoal">+ Goal</button><button class="btn alt" data-action="addHabit">+ Habit</button></div><div class="cards">'+card('Goals',state.goals.map(g=>'<div class="row"><span><b>'+esc(g.title)+'</b><br><small>'+esc(g.date||'No deadline')+'</small></span><span class="pill blue">'+g.progress+'%</span></div>').join('')||'<p class="muted">Wala pang goal.</p>')+card('Habits GitHub Style',state.habits.map(h=>'<div class="row"><span>'+esc(h.title)+'<br><small class="muted">Streak '+habitStreak(h)+' days</small></span><button class="btn alt" data-habit="'+h.id+'">✓ Today</button></div>').join(''))+'</div>'))}
function notes(){return layout('Notes & Vault',section('KNOWLEDGE','Notes + Secure Vault','<div class="toolbar"><button class="btn" data-action="addNote">+ Note</button><button class="btn alt" data-action="vault">Open Secure Vault</button></div><div class="cards">'+card('Notes',state.notes.map(n=>'<div class="row"><span><b>'+esc(n.title)+'</b><br><small class="muted">'+esc(n.content).slice(0,90)+'</small></span><button class="btn alt" data-note="'+n.id+'">Open</button></div>').join('')||'<p class="muted">Wala pang notes.</p>')+card('Vault Status','<p class="muted">AES-GCM 256 · PBKDF2 · auto-lock 5 mins</p><button class="btn" data-action="vault">Unlock / Setup Vault</button>')+'</div>'))}
function library(){return layout('Library',section('READ','Library','<div class="toolbar"><button class="btn" data-action="addBook">+ Add item</button></div><div class="grid">'+state.library.map(x=>card(esc(x.title),'<p class="muted">'+esc(x.author||'')+'</p><span class="pill '+(x.status==='Done'?'green':'blue')+'">'+esc(x.status||'Reading')+'</span>')).join('')+'</div>'))}
function clients(){const rec=state.clients.filter(x=>x.status!=='Paid').reduce((a,x)=>a+Number(x.amount||0),0);return layout('Client CRM',section('WORK','Client CRM','<div class="kpis"><div class="card kpi">Total receivable<strong>'+money(rec)+'</strong></div><div class="card kpi">Clients<strong>'+state.clients.length+'</strong></div></div><div class="toolbar"><button class="btn" data-action="addClient">+ Client</button></div><div class="card"><table class="table"><thead><tr><th>Client</th><th>Project</th><th>Amount</th><th>Status</th><th>Due</th></tr></thead><tbody>'+state.clients.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+esc(c.project)+'</td><td>'+money(c.amount)+'</td><td><span class="pill '+(c.status==='Paid'?'green':c.status==='Overdue'?'red':'orange')+'">'+c.status+'</span></td><td>'+esc(c.due||'—')+'</td></tr>').join('')+'</tbody></table></div>'))}
function analytics(){const tabs=[['overview','Overview'],['finance','Finance'],['productivity','Productivity'],['habits','Habits']];return layout('Analytics',section('INSIGHTS','Analytics & Insights','<div class="tabs">'+tabs.map(x=>'<button class="btn alt '+(analyticsTab===x[0]?'active':'')+'" data-atab="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>'+(analyticsTab==='finance'?aFinance():analyticsTab==='productivity'?aProductivity():analyticsTab==='habits'?aHabits():aOverview())+'<div class="toolbar"><button class="btn" data-action="analyticsExport">Export CSV/JSON/PNG</button></div>'))}
function aOverview(){const score=lifeScore(),arr=[];for(let i=89;i>=0;i--){const d=iso(new Date(Date.now()-i*864e5)),n=state.tasks.filter(x=>x.done&&x.completedAt?.slice(0,10)===d).length+state.focus.filter(x=>x.date===d).length;arr.push('<i class="'+(n>4?'l4':n>2?'l3':n?'l2':n>0?'l1':'')+'" title="'+d+'"></i>')}return '<div class="grid"><div class="card"><h3>Life Score</h3><div class="score">'+score+'</div><p class="muted">0–100 rule-based score</p></div><div class="card"><h3>Total Tasks Done</h3><div class="score">'+state.tasks.filter(x=>x.done).length+'</div></div><div class="card"><h3>Avg Daily Focus</h3><div class="score">'+Math.round(state.focus.reduce((a,x)=>a+x.minutes,0)/Math.max(1,30))+'m</div></div><div class="card"><h3>Money Saved This Month</h3><div class="score">'+money(savedMonth())+'</div></div></div><div class="card"><h3>90-day Activity</h3><div class="heat">'+arr.join('')+'</div></div><div class="card"><h3>Payapang Isip Insight</h3><p>'+esc(insights()[0]?.text||'Panatilihin ang steady na routine.')+'</p></div>'}
function aFinance(){const months=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const ym=d.toISOString().slice(0,7),v=state.finance.tx.filter(x=>x.type==='expense'&&x.date?.slice(0,7)===ym).reduce((a,x)=>a+Number(x.amount||0),0);months.push(v)}const total=months.reduce((a,b)=>a+b,0)||1;return '<div class="cards"><div class="card"><h3>6-month Spend</h3><div class="chart">'+months.map(v=>'<div class="vbar" style="height:'+Math.max(4,v/Math.max(...months,1)*100)+'%" title="'+money(v)+'"></div>').join('')+'</div></div><div class="card"><h3>Envelope Mix</h3><div class="pie"></div><p class="muted">Food · Bills · Padala · Luho · Ipon</p></div></div><div class="card"><h3>Forecast vs Actual</h3><p>Actual: <b>'+money(months.at(-1))+'</b> · Forecast: <b>'+money(months.at(-1)*1.03)+'</b></p></div>'}
function aProductivity(){const vals=[];for(let i=13;i>=0;i--){const d=iso(new Date(Date.now()-i*864e5));vals.push(state.tasks.filter(x=>x.done&&x.completedAt?.slice(0,10)===d).length)}return '<div class="card"><h3>14-day Task Flow</h3><div class="chart">'+vals.map(v=>'<div class="vbar" style="height:'+Math.max(4,v/Math.max(...vals,1)*100)+'%"></div>').join('')+'</div></div><div class="cards"><div class="card"><h3>Focus Analytics</h3><p>'+state.focus.length+' sessions · '+state.focus.reduce((a,x)=>a+x.minutes,0)+' minutes deep work.</p></div><div class="card"><h3>Project Velocity</h3><p>'+state.tasks.filter(x=>x.done).length+' completed tasks all time.</p></div></div>'}
function aHabits(){return '<div class="cards">'+card('Habit Completion',state.habits.map(h=>'<div class="vrow">'+esc(h.title)+' — '+habitRate(h)+'%</div>').join(''))+card('Streak Leaderboard',state.habits.slice().sort((a,b)=>habitStreak(b)-habitStreak(a)).map(h=>'<div class="row"><span>'+esc(h.title)+'</span><b>'+habitStreak(h)+' days</b></div>').join(''))+'</div><div class="card"><h3>Mood · 30 days</h3><svg class="linechart" viewBox="0 0 300 150"><polyline points="'+moodPoints()+'" fill="none" stroke="#6D8A70" stroke-width="4"/></svg></div>'}
function weekly(){const done=state.tasks.filter(x=>x.done&&days(x.completedAt?.slice(0,10)||x.date)<0&&days(x.completedAt?.slice(0,10)||x.date)>=-7).length,focus=state.focus.filter(x=>days(x.date)>=-7&&days(x.date)<=0).reduce((a,x)=>a+x.minutes,0),moods=state.journals.slice(-7).map(x=>x.mood).filter(Boolean);return layout('Weekly Review',section('REVIEW','Weekly Review','<div class="card"><h3>Last 7 days</h3><p>Tasks done: <b>'+done+'</b></p><p>Focus: <b>'+focus+' minutes</b></p><p>Mood entries: <b>'+moods.length+'</b></p><p>Finance gastos: <b>'+money(state.finance.tx.filter(x=>x.type==='expense'&&days(x.date)>=-7).reduce((a,x)=>a+Number(x.amount||0),0))+'</b></p><button class="btn" data-action="weeklyExport">Export PNG</button> <button class="btn alt" data-action="closing">Add Closing</button></div>'))}
function changelog(){const items=[['v4.1','Personal OS Final','APIs, connections, Taglish cleanup'],['v4.0','Analytics & Insights','Life Score, charts, insights'],['v3.0','Advanced Tools','Focus, Secure Vault, Command Palette, Weekly Review'],['v2.0','Core Personal OS','Prayer Guard, Budget Forecast, CRM, Closing'],['v1.0','Initial LifeHub launch','Personal organizer foundation']];return layout('Changelog',section('UPDATES','Changelog','<div>'+items.map(x=>'<div class="card" style="margin:10px 0"><span class="pill green">'+x[0]+'</span><h3>'+x[1]+'</h3><p class="muted">'+x[2]+'</p></div>').join('')+'</div>'))}
function lifeScore(){const t=state.tasks.length?state.tasks.filter(x=>x.done).length/state.tasks.length:0,b=state.finance.budgets.length?state.finance.budgets.filter(x=>x.spent<=x.limit).length/state.finance.budgets.length:1,h=state.habits.length?state.habits.reduce((a,x)=>a+habitRate(x),0)/state.habits.length/100:0,j=state.journals.length?Math.min(1,state.journals.length/14):0;return Math.round((t*.3+b*.25+h*.3+j*.15)*100)}
function insights(){const a=[];const over=state.finance.budgets.filter(x=>x.spent>x.limit);if(over.length)a.push({title:'May overspend',text:'Na-over ang '+over.map(x=>x.title).join(', ')+'. Bawasan muna ang gastos bago magdagdag.',action:'finance'});if(state.focus.length<3)a.push({title:'Deep work muna',text:'Subukan ang isang 25-minute focus session today.',action:'focus'});if(!a.length)a.push({title:'Steady progress',text:'Maayos ang takbo. Panatilihin ang small daily wins.',action:'analytics'});return a}
function savedMonth(){const m=iso().slice(0,7),inc=state.finance.tx.filter(x=>x.type==='income'&&x.date?.slice(0,7)===m).reduce((a,x)=>a+Number(x.amount||0),0);const exp=state.finance.tx.filter(x=>x.type==='expense'&&x.date?.slice(0,7)===m).reduce((a,x)=>a+Number(x.amount||0),0);return Math.max(0,inc-exp)}
function habitRate(h){let n=0;for(let i=0;i<30;i++){const d=iso(new Date(Date.now()-i*864e5));if(h.checks?.[d])n++}return Math.round(n/30*100)}
function habitStreak(h){let n=0;for(let i=0;i<365;i++){const d=iso(new Date(Date.now()-i*864e5));if(h.checks?.[d])n++;else if(i>0)break}return n}
function moodPoints(){const a=[];for(let i=29;i>=0;i--){const d=iso(new Date(Date.now()-i*864e5)),m=state.journals.find(x=>x.date===d)?.mood||'';const v=/great|happy|good|masaya/i.test(m)?5:/okay|ok|sakto/i.test(m)?3:/bad|sad|pagod|stress/i.test(m)?2:3;a.push((29-i)*10+' '+(130-v*20))}return a.join(' ')}
function nextPrayer(){const now=new Date(),map=[['Fajr',state.prayers.Fajr],['Dhuhr',state.prayers.Dhuhr],['Asr',state.prayers.Asr],['Maghrib',state.prayers.Maghrib],['Isha',state.prayers.Isha]];for(const [name,time] of map){const m=time.match(/(\d+):(\d+)\s*(AM|PM)/i);if(!m)continue;let h=+m[1]%12;if(m[3].toUpperCase()==='PM')h+=12;const t=new Date(now);t.setHours(h,+m[2],0,0);if(t>now)return{name,time,remaining:formatRemaining(t-now)}}const [name,time]=map[0];return{name,time,remaining:'bukas'}}
function formatRemaining(ms){const m=Math.max(0,Math.floor(ms/60000)),h=Math.floor(m/60);return h+'h '+m%60+'m'}
function formTask(){modalBox('Add Task','<div class="form-grid"><label class="full">Task<input id="fTitle" autofocus></label><label>Date<input id="fDate" type="date" value="'+iso()+'"></label><label>Priority<select id="fPri"><option>normal</option><option>high</option><option>low</option></select></label><label>Status<select id="fStatus"><option>todo</option><option>doing</option><option>blocked</option></select></label><label>Recurring<select id="fRepeat"><option value="">One-off</option><option>daily</option><option>weekly</option><option>monthly</option></select></label></div>','<button class="btn" data-save-task>Save Task</button>');modal.querySelector('[data-save-task]').onclick=()=>{const t={id:id(),title:document.getElementById('fTitle').value.trim(),date:document.getElementById('fDate').value,priority:document.getElementById('fPri').value,status:document.getElementById('fStatus').value,repeat:document.getElementById('fRepeat').value,done:false};if(!t.title)return;state.tasks.push(t);save();modal.innerHTML='';render()}}
function formEvent(){modalBox('Add Event','<div class="form-grid"><label class="full">Event<input id="eTitle"></label><label>Date<input id="eDate" type="date" value="'+iso()+'"></label><label>Time<input id="eTime" type="time"></label></div>','<button class="btn" data-save-event>Save Event</button>');modal.querySelector('[data-save-event]').onclick=()=>{const title=document.getElementById('eTitle').value.trim(),date=document.getElementById('eDate').value,time=document.getElementById('eTime').value;if(!title)return;state.events.push({id:id(),title,date,time});save();modal.innerHTML='';render()}}
function formHULUGAN(){modalBox('HULUGAN Tracker','<div class="form-grid"><label class="full">Pangalan<input id="hTitle"></label><label>Total amount<input id="hTotal" type="number"></label><label>Buwanang Hulog<input id="hMonthly" type="number"></label><label>Unang bayad<input id="hStart" type="date" value="'+iso()+'"></label></div>','<button class="btn" data-save-h>Save HULUGAN</button>');modal.querySelector('[data-save-h]').onclick=()=>{const total=+document.getElementById('hTotal').value,monthly=+document.getElementById('hMonthly').value;if(!total||!monthly)return;state.hulugan.push({id:id(),title:document.getElementById('hTitle').value||'HULUGAN',total,monthly,months:Math.ceil(total/monthly),paid:0,next:document.getElementById('hStart').value});save();modal.innerHTML='';render()}}
function formClient(){modalBox('Add Client','<div class="form-grid"><label>Client name<input id="cName"></label><label>Project<input id="cProject"></label><label>Amount PHP<input id="cAmount" type="number"></label><label>Status<select id="cStatus"><option>Pending</option><option>Paid</option><option>Overdue</option></select></label><label>Due<input id="cDue" type="date"></label></div>','<button class="btn" data-save-c>Save Client</button>');modal.querySelector('[data-save-c]').onclick=()=>{const c={id:id(),name:document.getElementById('cName').value,project:document.getElementById('cProject').value,amount:+document.getElementById('cAmount').value,status:document.getElementById('cStatus').value,due:document.getElementById('cDue').value};state.clients.push(c);if(c.status==='Paid')addIncome(c.amount,'Client · '+c.name);save();modal.innerHTML='';render()}}
function formClosing(){modalBox('Daily Closing Ritual','<div class="quote">'+esc(state.quote||'Kahit maliit ang progress, progress pa rin.')+'</div><div class="form-grid" style="margin-top:12px"><label>3 wins<textarea id="jWins"></textarea></label><label>Top 3 bukas<textarea id="jTomorrow"></textarea></label><label>Mood<input id="jMood" placeholder="Masaya / Okay / Pagod / Stress"></label></div>','<button class="btn" data-save-j>Save Closing</button>');modal.querySelector('[data-save-j]').onclick=()=>{state.journals.push({id:id(),date:iso(),wins:document.getElementById('jWins').value,tomorrow:document.getElementById('jTomorrow').value,mood:document.getElementById('jMood').value});save();modal.innerHTML='';toast('Closing saved');render()}}
function formNote(){modalBox('Add Note','<div class="form-grid"><label class="full">Title<input id="nTitle"></label><label class="full">Content<textarea id="nContent"></textarea></label></div>','<button class="btn" data-save-n>Save Note</button>');modal.querySelector('[data-save-n]').onclick=()=>{state.notes.push({id:id(),title:document.getElementById('nTitle').value,content:document.getElementById('nContent').value,date:iso()});save();modal.innerHTML='';render()}}
function formGoal(){modalBox('Add Goal','<div class="form-grid"><label class="full">Goal<input id="gTitle"></label><label>Deadline<input id="gDate" type="date"></label><label>Progress %<input id="gProgress" type="number" min="0" max="100" value="0"></label></div>','<button class="btn" data-save-g>Save Goal</button>');modal.querySelector('[data-save-g]').onclick=()=>{state.goals.push({id:id(),title:document.getElementById('gTitle').value,date:document.getElementById('gDate').value,progress:+document.getElementById('gProgress').value});save();modal.innerHTML='';render()}}
function formHabit(){modalBox('Add Habit','<label>Habit<input id="habTitle"></label>','<button class="btn" data-save-hab>Save Habit</button>');modal.querySelector('[data-save-hab]').onclick=()=>{state.habits.push({id:id(),title:document.getElementById('habTitle').value,checks:{}});save();modal.innerHTML='';render()}}
function formBook(){modalBox('Add Library Item','<div class="form-grid"><label>Title<input id="bTitle"></label><label>Author<input id="bAuthor"></label><label>Status<select id="bStatus"><option>Reading</option><option>Done</option><option>Wishlist</option></select></label></div>','<button class="btn" data-save-b>Save</button>');modal.querySelector('[data-save-b]').onclick=()=>{state.library.push({id:id(),title:document.getElementById('bTitle').value,author:document.getElementById('bAuthor').value,status:document.getElementById('bStatus').value});save();modal.innerHTML='';render()}}
function addIncome(n,desc){state.finance.income+=Number(n)||0;state.finance.tx.push({id:id(),type:'income',amount:Number(n)||0,date:iso(),desc})}
function formMoney(type){modalBox(type==='income'?'Add Income':'Add Expense','<div class="form-grid"><label>Amount<input id="mAmt" type="number"></label><label>Envelope<select id="mEnv">'+state.finance.budgets.map(x=>'<option>'+esc(x.title)+'</option>').join('')+'</select></label><label class="full">Description<input id="mDesc"></label></div>','<button class="btn" data-save-money>Save</button>');modal.querySelector('[data-save-money]').onclick=()=>{const n=+document.getElementById('mAmt').value,env=document.getElementById('mEnv').value;if(!n)return;if(type==='income')addIncome(n,document.getElementById('mDesc').value);else{const b=state.finance.budgets.find(x=>x.title===env);if(b)b.spent+=n;state.finance.tx.push({id:id(),type:'expense',amount:n,date:iso(),desc:document.getElementById('mDesc').value,envelope:env})}save();modal.innerHTML='';render()}}
function quick(){modalBox('Quick Capture','<input id="qText" style="width:100%" autofocus placeholder="Task, note, idea...">','<button class="btn" data-save-q>Save</button>');modal.querySelector('[data-save-q]').onclick=()=>{const v=document.getElementById('qText').value.trim();if(v){state.tasks.push({id:id(),title:v,date:iso(),priority:'normal',status:'todo',done:false});save()}modal.innerHTML='';render()}}
function command(){modalBox('Command Palette','<input id="cmd" style="width:100%" autofocus placeholder="Search tasks, notes, clients..."><div id="cmdList" style="margin-top:12px"></div>');const inp=document.getElementById('cmd'),list=document.getElementById('cmdList'),items=[['Jump to Budget','finance'],['Add 500 ipon','ipon'],['Mark all today done','done'],['Start focus on top task','focus'],['Export data','export'],...state.tasks.map(x=>[x.title,'task']),...state.notes.map(x=>[x.title,'note']),...state.clients.map(x=>[x.name,'client'])];function draw(){const q=inp.value.toLowerCase();list.innerHTML=items.filter(x=>x[0].toLowerCase().includes(q)).slice(0,12).map(x=>'<button class="btn alt" style="display:block;width:100%;margin:5px 0;text-align:left" data-cmdv="'+esc(x[1])+'">'+esc(x[0])+'</button>').join('')||'<p class="muted">Walang match.</p>';list.querySelectorAll('[data-cmdv]').forEach(b=>b.onclick=()=>runCommand(b.dataset.cmdv))}inp.oninput=draw;draw()}
function runCommand(c){if(c==='finance')nav('finance');else if(c==='ipon'){const b=state.finance.budgets.find(x=>x.title==='Ipon');if(b)b.spent+=500;state.finance.tx.push({id:id(),type:'expense',amount:500,date:iso(),desc:'Command · Ipon',envelope:'Ipon'});save();modal.innerHTML='';toast('₱500 added sa Ipon');render()}else if(c==='done'){state.tasks.filter(x=>x.date===iso()).forEach(x=>{x.done=true;x.completedAt=new Date().toISOString()});save();modal.innerHTML='';render()}else if(c==='focus')startFocus(state.tasks.find(x=>!x.done)?.id);else if(c==='export')exportJSON();else{modal.innerHTML=''}}
async function startFocus(taskId){const t=state.tasks.find(x=>x.id==taskId)||state.tasks.find(x=>!x.done);if(!t)return toast('Walang task na puwedeng i-focus.');focusState={task:t,seconds:25*60,paused:false,started:Date.now()};document.body.insertAdjacentHTML('beforeend','<div class="focus" id="focus"><div class="focus-inner"><div class="eyebrow">FOCUS MODE</div><h1>'+esc(t.title)+'</h1><div class="timer" id="timer"><b id="clock">25:00</b></div><button class="btn" id="pause">Pause</button> <button class="btn alt" id="reset">Reset</button> <button class="btn alt" id="skip">Finish</button></div></div>');document.getElementById('pause').onclick=()=>{focusState.paused=!focusState.paused;document.getElementById('pause').textContent=focusState.paused?'Resume':'Pause'};document.getElementById('reset').onclick=()=>{focusState.seconds=25*60};document.getElementById('skip').onclick=()=>finishFocus();focusTimer=setInterval(tick,1000);tick()}
function tick(){if(!focusState||focusState.paused)return;focusState.seconds--;const total=1500,p=Math.max(0,Math.min(100,(total-focusState.seconds)/total*100)),m=Math.floor(Math.max(0,focusState.seconds)/60),s=Math.max(0,focusState.seconds)%60;const c=document.getElementById('clock'),ring=document.getElementById('timer');if(c)c.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');if(ring)ring.style.setProperty('--p',p+'%');if(focusState.seconds<=0)finishFocus()}
function finishFocus(){if(!focusState)return;clearInterval(focusTimer);state.focus.push({id:id(),date:iso(),minutes:25,taskId:focusState.task.id});const h=state.habits.find(x=>x.title.toLowerCase()==='deep work');if(h)h.checks[iso()]=true;save();try{const a=new AudioContext(),o=a.createOscillator();o.frequency.value=880;o.connect(a.destination);o.start();o.stop(a.currentTime+.25)}catch(e){}document.getElementById('focus')?.remove();focusState=null;toast('Focus session saved + Deep Work');render()}
async function vault(){const verifier='tubalhub_vault_verifier';const saltKey='tubalhub_vault_salt';modalBox('Secure Vault V2','<p class="muted">AES-GCM 256 + PBKDF2. Master password minimum 8 chars. Auto-lock after 5 minutes.</p><input id="vp" type="password" style="width:100%" placeholder="Master password"><div id="vaultItems" style="margin-top:14px"></div>','<button class="btn" data-vault-go>Unlock</button>');modal.querySelector('[data-vault-go]').onclick=async()=>{const p=document.getElementById('vp').value;if(p.length<8)return toast('Minimum 8 characters.');const salt=localStorage.getItem(saltKey)||crypto.getRandomValues(new Uint8Array(16));const saltB=typeof salt==='string'?b64dec(salt):salt;localStorage.setItem(saltKey,typeof salt==='string'?salt:b64(salt));const key=await derive(p,saltB);const test=localStorage.getItem(verifier);if(test){try{await decrypt(JSON.parse(test),key)}catch(e){return toast('Master password mali.')}}else localStorage.setItem(verifier,JSON.stringify(await encrypt('TUBAL HUB VAULT',key)));const raw=localStorage.getItem('tubalhub_vault_items')||'[]';let items=[];try{items=JSON.parse(raw)}catch(e){}modal.querySelector('#vaultItems').innerHTML='<button class="btn" id="addV">+ Password</button>'+items.map(x=>'<div class="row"><span>'+esc(x.label)+'</span><button class="btn alt" data-v="'+x.id+'">Reveal</button></div>').join('');modal.querySelector('#addV').onclick=async()=>{const label=prompt('Label');const value=prompt('Value');if(label&&value){items.push({id:id(),label,value:await encrypt(value,key)});localStorage.setItem('tubalhub_vault_items',JSON.stringify(items));toast('Vault item saved')}};modal.querySelectorAll('[data-v]').forEach(b=>b.onclick=async()=>{const x=items.find(i=>i.id==b.dataset.v);if(x)alert(await decrypt(x.value,key))})}}
async function derive(p,s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:100000,hash:'SHA-256'},k,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(v,k){const iv=crypto.getRandomValues(new Uint8Array(12)),d=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(v));return{iv:b64(iv),data:b64(new Uint8Array(d))}}
async function decrypt(x,k){const d=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64dec(x.iv)},k,b64dec(x.data));return new TextDecoder().decode(d)}
function b64(a){let s='';new Uint8Array(a).forEach(x=>s+=String.fromCharCode(x));return btoa(s)}
function b64dec(s){const b=atob(s);return Uint8Array.from(b,c=>c.charCodeAt(0))}
function exportJSON(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tubal-hub-v4.1-backup.json';a.click()}
function exportAnalytics(){const csv=(a,cols)=>[cols.join(','),...a.map(x=>cols.map(k=>JSON.stringify(x[k]??'')).join(','))].join('\n');const files=[['tasks.csv',csv(state.tasks,['id','title','date','done','priority'])],['finance.csv',csv(state.finance.tx,['type','amount','date','desc'])],['habits.csv',csv(state.habits,['id','title'])]];files.forEach(([n,c])=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:'text/csv'}));a.download=n;a.click()});const blob=new Blob([JSON.stringify({lifeScore:lifeScore(),insights:insights()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tubal-hub-analytics.json';a.click();const cv=document.createElement('canvas');cv.width=1080;cv.height=1350;const x=cv.getContext('2d');x.fillStyle='#FCF9F5';x.fillRect(0,0,1080,1350);x.fillStyle='#111';x.font='800 56px Inter';x.fillText('TUBAL HUB v4.1',70,100);x.font='700 42px Inter';x.fillText('Analytics Report',70,170);x.font='500 28px Inter';x.fillText('Life Score: '+lifeScore()+'/100',70,250);x.fillText('Tasks done: '+state.tasks.filter(t=>t.done).length,70,310);x.fillText('Focus minutes: '+state.focus.reduce((a,f)=>a+f.minutes,0),70,370);x.fillText('Saved this month: '+money(savedMonth()),70,430);cv.toBlob(b=>{const z=document.createElement('a');z.href=URL.createObjectURL(b);z.download='tubal-hub-analytics.png';z.click()})}
function weeklyPNG(){const cv=document.createElement('canvas');cv.width=1080;cv.height=1350;const x=cv.getContext('2d');x.fillStyle='#FCF9F5';x.fillRect(0,0,1080,1350);x.fillStyle='#111';x.font='800 56px Inter';x.fillText('TUBAL HUB · WEEKLY REVIEW',70,110);x.font='500 30px Inter';x.fillText('Tasks done: '+state.tasks.filter(t=>t.done).length,70,220);x.fillText('Focus: '+state.focus.reduce((a,f)=>a+f.minutes,0)+' min',70,280);x.fillText('Mood entries: '+state.journals.length,70,340);cv.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='weekly-review.png';a.click()})}
function onboarding(){modalBox('Welcome sa TUBAL HUB v4.1','<p class="muted">One-time setup lang. Taglish only.</p><div class="form-grid"><label>Name<input id="onName" value="'+esc(state.name)+'"></label><label>City<select id="onCity"><option>Davao</option><option>Quezon City</option></select></label><label>Currency<select id="onCur"><option>PHP</option></select></label></div>','<button class="btn" id="onSave">Start Personal OS</button>');document.getElementById('onSave').onclick=()=>{state.name=document.getElementById('onName').value.trim()||'Ar-ar Tubal';state.city=document.getElementById('onCity').value;state.currency=document.getElementById('onCur').value;state.setup=true;save();modal.innerHTML='';render();refreshAPIs(true)}}
async function refreshAPIs(force=false){const now=Date.now();try{const p=await fetch('https://api.aladhan.com/v1/timingsByCity?city='+encodeURIComponent(state.city)+'&country=Philippines&method=3');if(!p.ok)throw 0;const j=await p.json();if(j.data?.timings){state.prayers={Fajr:j.data.timings.Fajr,Dhuhr:j.data.timings.Dhuhr,Asr:j.data.timings.Asr,Maghrib:j.data.timings.Maghrib,Isha:j.data.timings.Isha};state.api.prayer=true;localStorage.setItem('tubalhub_prayer',JSON.stringify({at:now,data:state.prayers}))}}catch(e){state.api.prayer=false}try{const y=new Date().getFullYear(),h=await fetch('https://date.nager.at/api/v3/PublicHolidays/'+y+'/PH');if(!h.ok)throw 0;state.holidays=await h.json();state.api.holidays=true;localStorage.setItem('tubalhub_holidays',JSON.stringify({at:now,data:state.holidays}))}catch(e){const c=JSON.parse(localStorage.getItem('tubalhub_holidays')||'null');if(c?.data)state.holidays=c.data}try{const w=await fetch('https://api.open-meteo.com/v1/forecast?latitude=7.07&longitude=125.60&current_weather=true');if(!w.ok)throw 0;const j=await w.json();state.weather={temperature:j.current_weather?.temperature??32};localStorage.setItem('tubalhub_weather',JSON.stringify({at:now,data:state.weather}))}catch(e){const c=JSON.parse(localStorage.getItem('tubalhub_weather')||'null');state.weather=c?.data||{temperature:32}}try{const q=await fetch('https://api.quotable.io/random');if(!q.ok)throw 0;const j=await q.json();state.quote=j.content||'Kahit maliit ang progress, progress pa rin.';localStorage.setItem('tubalhub_quote',JSON.stringify({at:now,data:state.quote}))}catch(e){const c=JSON.parse(localStorage.getItem('tubalhub_quote')||'null');state.quote=c?.data||'Kahit maliit ang progress, progress pa rin.'}save();if(route==='calendar'||route==='home'||route==='weekly')render()}
function apiCacheLoad(){const max=86400000;for(const [key,prop] of [['tubalhub_prayer','prayers'],['tubalhub_holidays','holidays'],['tubalhub_weather','weather'],['tubalhub_quote','quote']]){try{const c=JSON.parse(localStorage.getItem(key)||'null');if(c&&Date.now()-c.at<max)state[prop]=c.data}catch(e){}}state.prayers={...PRAYER_FALLBACK,...state.prayers};state.weather=state.weather||{temperature:32};state.quote=state.quote||'Kahit maliit ang progress, progress pa rin.'}
function markTask(idv,done){const t=state.tasks.find(x=>x.id==idv);if(!t)return;t.done=done;t.completedAt=done?new Date().toISOString():null;if(done&&t.repeat){const nd=new Date(t.date);if(t.repeat==='daily')nd.setDate(nd.getDate()+1);if(t.repeat==='weekly')nd.setDate(nd.getDate()+7);if(t.repeat==='monthly')nd.setMonth(nd.getMonth()+1);state.tasks.push({...t,id:id(),date:iso(nd),done:false,completedAt:null})}save();render()}
function addActions(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=()=>nav(x.dataset.route));document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>markTask(x.dataset.task,x.checked));document.querySelectorAll('[data-focus]').forEach(x=>x.onclick=()=>startFocus(x.dataset.focus));document.querySelectorAll('[data-action]').forEach(x=>x.onclick=()=>act(x.dataset.action));document.querySelectorAll('[data-atab]').forEach(x=>x.onclick=()=>{analyticsTab=x.textContent.toLowerCase().startsWith('habit')?'habits':x.textContent.toLowerCase();render()});document.querySelectorAll('[data-cal]').forEach(x=>x.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+Number(x.dataset.cal));render()});document.querySelectorAll('[data-habit]').forEach(x=>x.onclick=()=>{const h=state.habits.find(h=>h.id==x.dataset.habit);if(h){h.checks[iso()]=!h.checks[iso()];save();render()}});document.querySelectorAll('[data-menu]').forEach(x=>x.onclick=()=>{const s=document.querySelector('.sidebar');if(s){s.style.display=s.style.display==='block'?'none':'block';s.style.position='fixed'}});document.querySelectorAll('[data-cmd]').forEach(x=>x.onclick=command);document.querySelectorAll('[data-focus-top]').forEach(x=>x.onclick=()=>startFocus(state.tasks.find(t=>!t.done)?.id));document.querySelectorAll('[data-export]').forEach(x=>x.onclick=exportJSON);document.querySelectorAll('[data-import]').forEach(x=>x.onclick=()=>document.getElementById('importFile')?.click())}
function act(a){if(a==='quick')quick();else if(a==='addTask')formTask();else if(a==='addEvent')formEvent();else if(a==='addHULUGAN')formHULUGAN();else if(a==='addClient')formClient();else if(a==='closing')formClosing();else if(a==='addNote')formNote();else if(a==='addGoal')formGoal();else if(a==='addHabit')formHabit();else if(a==='addBook')formBook();else if(a==='addIncome')formMoney('income');else if(a==='addExpense')formMoney('expense');else if(a==='vault')vault();else if(a==='refreshAPIs')refreshAPIs(true);else if(a==='analyticsExport')exportAnalytics();else if(a==='weeklyExport')weeklyPNG();else if(a==='focus')startFocus(state.tasks.find(x=>!x.done)?.id)}
function render(){if(!state.setup){onboarding();return}let b={home:dashboard,calendar,tasks,finance,goals,notes,library,clients,analytics,weekly,changelog}[route]||dashboard;app.innerHTML=b();addActions()}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();command()}if(e.key==='Escape'){modal.innerHTML='';document.getElementById('focus')?.remove();if(focusTimer){clearInterval(focusTimer);focusTimer=null}}});
document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);Object.assign(state,x);save();render();toast('Import complete')}catch(err){toast('Invalid backup')}};r.readAsText(f)};
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});
apiCacheLoad();render();setTimeout(()=>refreshAPIs(false),500);setInterval(()=>refreshAPIs(false),86400000);setInterval(()=>{if(new Date().getDay()===0&&new Date().getHours()===20){state.api.weekly=true;save()}},3600000);
