const K='lifehub-habits-v1',now=new Date(),iso=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const defaults=[['Tubig 8 baso','💧','Health','daily','08:00'],['Dasal 5x','🙏','Prayers','daily','06:00'],['Exercise 30min','🏃','Health','daily','17:30'],['Magbasa libro','📚','Work','daily','21:00'],['Ipon ₱100','💰','Work','weekly','18:00'],['Ayos kama','🛏️','Family','daily','07:00']];
const make=(a,i)=>({id:Date.now()+i,name:a[0],icon:a[1],category:a[2],goal:a[3],reminder:a[4],notes:'Small note para sa sarili mo.',checks:{}});
let habits=JSON.parse(localStorage.getItem(K)||'null');if(!habits){habits=defaults.map(make);let base=new Date(now);for(let h of habits){for(let i=1;i<18;i+=3){let d=new Date(base);d.setDate(d.getDate()-i);h.checks[iso(d)]=true}}localStorage.setItem(K,JSON.stringify(habits))}
let category='All',view='week',selected=habits[0]?.id||null,icon='✨';
const save=()=>localStorage.setItem(K,JSON.stringify(habits));
const monday=d=>{let x=new Date(d),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x};
const days7=()=>{let m=monday(now);return Array.from({length:7},(_,i)=>{let d=new Date(m);d.setDate(m.getDate()+i);return d})};
const streak=h=>{let n=0,d=new Date(now);while(h.checks[iso(d)]){n++;d.setDate(d.getDate()-1)}return n};
const best=h=>{let keys=Object.keys(h.checks).filter(k=>h.checks[k]).sort(),max=0,cur=0,prev=null;for(const k of keys){if(prev){let a=new Date(prev),b=new Date(k);if((b-a)/86400000===1)cur++;else cur=1}else cur=1;max=Math.max(max,cur);prev=k}return max};
function render(){document.title='LifeHub Habit Tracker';$('#today').textContent=new Intl.DateTimeFormat('fil-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(now);renderStats();renderHabits();renderGraph();renderDetail();bind()}
function renderStats(){let total=habits.length*7,done=habits.reduce((a,h)=>a+days7().filter(d=>h.checks[iso(d)]).length,0),pct=total?Math.round(done/total*100):0;let cs=habits.length?Math.max(...habits.map(streak)):0,bs=habits.length?Math.max(...habits.map(best)):0;$('#currentStreak').textContent=cs;$('#bestStreak').textContent=bs;$('#completion').textContent=pct+'%';$('#ring').style.background='conic-gradient(#7EC8A0 0 '+pct+'%,#eee9e2 '+pct+'% 100%)'}
function renderHabits(){let list=habits.filter(h=>category==='All'||h.category===category);if(!list.length){$('#habitList').innerHTML='<div class="empty">Wala pa habit, add ka muna besh</div>';return}let ds=days7();$('#habitList').innerHTML=list.map(h=>'<div class="habit"><div class="habit-icon">'+h.icon+'</div><div><div class="habit-name">'+esc(h.name)+'</div><div class="habit-meta">'+esc(h.category)+' · 🔥 '+streak(h)+' day streak · '+h.goal+'</div></div><div class="checks">'+ds.map(d=>'<button class="check '+(h.checks[iso(d)]?'on ':'')+(iso(d)===iso(now)?'today':'')+'" data-id="'+h.id+'" data-date="'+iso(d)+'" title="'+fmt(d)+'">'+(h.checks[iso(d)]?'✓':'')+'</button>').join('')+'</div></div>').join('')}
function renderGraph(){let end=new Date(now),start=new Date(end);start.setDate(end.getDate()-364);let cells=[];for(let i=0;i<365;i++){let d=new Date(start);d.setDate(start.getDate()+i);let score=habits.length?habits.filter(h=>h.checks[iso(d)]).length/habits.length:0;let lvl=score===0?'':score<=.25?'l1':score<=.5?'l2':score<=.75?'l3':'l4';cells.push('<div class="cell '+lvl+'" title="'+fmt(d)+' · '+Math.round(score*100)+'%"></div>')}$('#graph').innerHTML=cells.join('')}
function renderDetail(){let h=habits.find(x=>x.id===selected);if(!h){$('#detail').innerHTML='<div class="empty">Pumili ng habit para makita ang details.</div>';return}let hist=Object.keys(h.checks).filter(k=>h.checks[k]).sort().reverse().slice(0,8);$('#detail').innerHTML='<div class="eyebrow">HABIT DETAIL</div><h3>'+h.icon+' '+esc(h.name)+'</h3><div class="detail-stat"><div><b>'+streak(h)+'</b><span>Current streak</span></div><div><b>'+best(h)+'</b><span>Best streak</span></div><div><b>'+Object.keys(h.checks).filter(k=>h.checks[k]).length+'</b><span>Total check-ins</span></div></div><div class="notes"><b>Notes</b><br>'+esc(h.notes||'Walang notes pa.')+'</div><p class="muted">Recent history</p><div class="pills">'+hist.map(x=>'<span class="pill">'+fmt(new Date(x+'T00:00:00'))+'</span>').join('')+'</div>'}
function bind(){$$('.check').forEach(b=>b.onclick=()=>{let h=habits.find(x=>x.id==b.dataset.id);if(h){if(h.checks[b.dataset.date])delete h.checks[b.dataset.date];else h.checks[b.dataset.date]=true;selected=h.id;save();render()}});$$('.habit').forEach((row,i)=>row.onclick=e=>{if(!e.target.classList.contains('check')){let list=habits.filter(h=>category==='All'||h.category===category);selected=list[i]?.id;renderDetail()}});$$('.pill[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;$$('.pill[data-cat]').forEach(x=>x.classList.toggle('active',x===b));renderHabits()});$$('.view-toggle button').forEach(b=>b.onclick=()=>{view=b.dataset.view;$$('.view-toggle button').forEach(x=>x.classList.toggle('active',x===b));renderHabits()});$$('#icons button').forEach(b=>b.onclick=()=>{$$('#icons button').forEach(x=>x.classList.remove('active'));b.classList.add('active');icon=b.textContent})}
function openModal(){$('#modal').classList.add('open');$('#name').focus()}
$('#addHabit').onclick=openModal;$('#close').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};$('#saveHabit').onclick=()=>{let name=$('#name').value.trim();if(!name)return;habits.push({id:Date.now(),name,icon,category:$('#cat').value,goal:$('#goal').value,reminder:$('#reminder').value,notes:'Small note para sa sarili mo.',checks:{}});selected=habits.at(-1).id;save();$('#modal').classList.remove('open');$('#name').value='';render()};
function fmt(d){return new Intl.DateTimeFormat('fil-PH',{month:'short',day:'numeric'}).format(d)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
render();