const KEY='tubalhub_v2_os',TODAY=iso(new Date());
const PRAYERS={fajr:'4:30 AM',dhuhr:'12:00 PM',asr:'3:30 PM',maghrib:'6:00 PM',isha:'7:15 PM'};
const COLORS=['orange','green','blue','pink','yellow'];
const uid=()=>Date.now()+Math.random();
const iso=d=>{const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const days=(a,b=new Date(TODAY+'T00:00:00'))=>Math.round((new Date(a+'T00:00:00')-b)/86400000);
const money=(n,c='PHP')=>new Intl.NumberFormat('en-PH',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(n)||0);
const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('fil-PH',{month:'short',day:'numeric',year:'numeric'}):'—';

const seed={
 profile:{name:'',city:'Davao City',currency:'PHP',prayerGuard:true,setup:false},
 tasks:[
  {id:1,title:'Bayaran PLDT',date:TODAY,priority:'high',category:'Finance',project:'Life Admin',done:false,recurring:'monthly'},
  {id:2,title:'Submit portfolio',date:TODAY,priority:'mid',category:'Work',project:'Portfolio',done:false,recurring:'none'},
  {id:3,title:'Tawagan si Mama',date:TODAY,priority:'low',category:'Family',project:'Family',done:false,recurring:'none'}
 ],
 events:[],projects:[{id:1,title:'Portfolio',tasksTotal:5},{id:2,title:'Home Reset',tasksTotal:6}],
 renewals:[{id:1,title:'PhilHealth',date:iso(new Date(Date.now()+12*86400000)),type:'Insurance'},{id:2,title:'Driver License',date:iso(new Date(Date.now()+24*86400000)),type:'ID'}],
 budgets:[{title:'Food',spent:6200,limit:9000},{title:'Bills',spent:4100,limit:6000},{title:'Padala',spent:3500,limit:5000},{title:'Luho',spent:1200,limit:2500}],
 finance:{mode:'payable',income:30000,transactions:[]},
 installments:[{id:1,title:'Sample Plan',currency:'PHP',total:12000,monthly:2000,first:TODAY,paid:0}],
 birthdays:[{id:1,name:'Mama',date:'12-03',emoji:'🌷'},{id:2,name:'Ate',date:'10-18',emoji:'🎂'}],
 goals:[{id:1,title:'Build Portfolio',category:'Career',date:'2026-12-15',subs:[['Choose projects',true],['Case studies',false],['Publish',false]]}],
 habits:[{id:1,title:'Tubig 8 baso',icon:'💧',checks:{}},{id:2,title:'Dasal 5x',icon:'🤲',checks:{}},{id:3,title:'Exercise 30min',icon:'🏃',checks:{}}],
 notes:[{id:1,type:'Tips',title:'Auto-debit after sweldo',content:'Schedule bills and savings after payday.',tags:['money'],pinned:true,date:TODAY}],
 library:[{id:1,type:'Books',title:'Atomic Habits',author:'James Clear',status:'Reading',rating:5,read:142,total:320}],
 clients:[],captures:[],journals:[],settings:{closingEnabled:true,prayerGuard:true}
};
let S=load();migrateV3();let route=location.hash.slice(1)||'home';
function load(){try{return Object.assign(structuredClone(seed),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function go(r){route=r;location.hash=r;render()}
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});

const navItems=[
 ['home','⌂','Home'],['lifehub','◫','LifeHub'],['calendar','▦','Calendar'],['budget','₱','Budget'],['work','▤','Clients & Invoices'],['lab','✦','Lab']
];
function sidebar(){
 return '<aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">TH</div><div><b>TUBAL HUB v2</b><small>Personal OS · Ar-ar Tubal</small></div></div><nav class="nav"><div class="nav-section">Personal OS</div>'+navItems.map(n=>'<button class="'+(route===n[0]?'active':'')+'" data-route="'+n[0]+'"><span class="nav-icon">'+n[1]+'</span>'+n[2]+'</button>').join('')+'<div class="nav-section">Tools</div><button data-action="quick">⌘K &nbsp; Quick Capture</button><button data-action="export">⇩ &nbsp; Export JSON</button><button data-action="import">⇧ &nbsp; Import JSON</button><button data-action="settings">⚙ &nbsp; Settings</button></nav><div class="side-foot">Kaya pa. Tara. Ayos lang.<br>Offline-first · localStorage · no tracking</div></aside>'
}
function top(title){
 return '<header class="top"><div class="top-left"><button class="mobile-menu" id="mobileMenu">☰</button><div><div class="eyebrow">TUBAL HUB v2</div><h1>'+esc(title)+'</h1></div></div><div class="date">'+new Intl.DateTimeFormat('fil-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(new Date())+'</div></header>'
}
function shell(title,body){
 return '<div class="app">'+sidebar()+'<main class="main">'+top(title)+'<div class="page active">'+body+'</div><footer class="footer"><span>Tubal Hub by Ar-ar Tubal — MIT 2026</span><a href="https://github.com/tubalrr/tubalhub" target="_blank" rel="noopener">GitHub</a></footer></main><div class="mobile-bottom">'+navItems.slice(0,5).map(n=>'<button class="'+(route===n[0]?'active':'')+'" data-route="'+n[0]+'">'+n[1]+'<br>'+n[2].split(' ')[0]+'</button>').join('')+'</div></div>'
}
function section(k,t,body){return '<div class="section-head"><div><div class="eyebrow">'+k+'</div><h2>'+t+'</h2></div></div>'+body}
function cardList(a,empty='Wala pa, add ka muna besh'){return a.length?a:[]}

function home(){
 const overdue=S.tasks.filter(t=>!t.done&&t.date<TODAY).length,today=S.tasks.filter(t=>!t.done&&t.date===TODAY).length,week=S.tasks.filter(t=>!t.done&&days(t.date)>=0&&days(t.date)<7).length,renew=S.renewals.filter(x=>days(x.date)>=0&&days(x.date)<30).length;
 const next=nextPrayer();
 const last=S.journals[S.journals.length-1];
 return shell('Home','<div class="hero"><div><div class="eyebrow">PERSONAL OS ✦</div><h2>'+(S.profile.name?'Hi, '+esc(S.profile.name)+'. ':'')+'Pangarap mo, tuparin mo.</h2><p>One calm place para sa tasks, pera, work, habits at araw-araw na buhay.</p></div><button class="btn" data-action="quick">+ Quick Capture</button></div>'+
 '<div class="kpis"><div class="card kpi">Overdue<strong>'+overdue+'</strong><span class="muted">Needs attention</span></div><div class="card kpi">Today<strong>'+today+'</strong><span class="muted">For today</span></div><div class="card kpi">This Week<strong>'+week+'</strong><span class="muted">Keep moving</span></div><div class="card kpi">Renewals &lt;30d<strong>'+renew+'</strong><span class="muted">Plan ahead</span></div></div>'+
 '<div class="cards"><div class="card"><div class="head"><h3>Next Prayer</h3><span class="pill yellow">'+esc(S.profile.city)+'</span></div><h2>'+next.name+' · '+next.time+'</h2><p class="muted">'+next.remaining+' remaining · Guard '+(S.settings.prayerGuard?'ON':'OFF')+'</p></div>'+
 '<div class="card"><div class="head"><h3>Daily Closing</h3><span class="pill pink">'+journalStreak()+' days</span></div>'+(last?'<p>'+esc(last.wins)+'</p><small class="muted">'+last.date+' · '+last.mood+'</small>':'<p class="muted">Wala pang closing note today.</p>')+'<div style="margin-top:12px"><button class="btn" data-action="closing">Mag-close ng araw</button></div></div></div>'+
 '<div class="cards" style="margin-top:14px"><div class="card"><div class="head"><h3>Today Tasks</h3><button class="btn alt" data-route="lifehub">Open LifeHub</button></div>'+S.tasks.filter(t=>!t.done).slice(0,6).map(taskRow).join('')+(S.tasks.filter(t=>!t.done).length?'':'<div class="empty">Wala pa, add ka muna besh.</div>')+'</div>'+
 '<div class="card"><div class="head"><h3>Latest Closing</h3><span class="muted">Journal</span></div>'+(last?'<b>'+esc(last.wins)+'</b><p class="muted">'+esc(last.tomorrow)+'</p>':'<div class="empty">Kumusta araw mo? 🌙</div>')+'</div></div>')
}
function taskRow(t){return '<div class="row"><label class="check"><input type="checkbox" data-task="'+t.id+'" '+(t.done?'checked':'')+'><span class="'+(t.done?'done':'')+'">'+esc(t.title)+'</span></label><span style="display:flex;gap:6px;align-items:center"><button class="btn alt focus-task" data-focus="'+t.id+'">Focus</button><span class="pill '+(t.priority==='high'?'orange':t.priority==='low'?'green':'blue')+'">'+t.priority+'</span></span></div>'}
function calendar(){
 const d=new Date(),y=d.getFullYear(),m=d.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<div></div>';for(let n=1;n<=last;n++){let date=iso(new Date(y,m,n)),items=[...S.events.filter(e=>e.date===date),...S.tasks.filter(t=>t.date===date).map(t=>({title:t.title,color:'blue'}))];cells+='<div class="day '+(date===TODAY?'today':'')+'"><b>'+n+'</b>'+items.slice(0,5).map(e=>'<span class="chip '+(e.color||'blue')+'">'+esc(e.title)+'</span>').join('')+'</div>'}
 return shell('Calendar',section('YOUR DAYS','Calendar','<div class="toolbar"><button class="btn" data-action="addEvent">+ Add event</button><button class="btn alt" data-action="addTask">+ Task</button></div>'+(S.settings.prayerGuard?'<div class="prayer-line">🕌 Prayer · Fajr '+PRAYERS.fajr+' · Dhuhr '+PRAYERS.dhuhr+' · Asr '+PRAYERS.asr+' · Maghrib '+PRAYERS.maghrib+' · Isha '+PRAYERS.isha+'</div>':'')+'<div class="card" style="margin-top:14px"><div class="head"><h3>'+new Intl.DateTimeFormat('fil-PH',{month:'long',year:'numeric'}).format(d)+'</h3><span class="muted">Lun–Lin</span></div><div class="calendar-wrap"><div class="calendar-grid">'+['Lun','Mar','Miy','Huw','Biy','Sab','Lin'].map(x=>'<div class="weekday">'+x+'</div>').join('')+cells+'</div></div></div>'))
}
function budget(){
 const pred=forecast(),income=Number(S.finance.income)||0,remain=income-pred.total;
 return shell('Budget',section('MONEY CHECK','Budget','<div class="toolbar"><button class="btn" data-action="addBudget">+ Envelope</button><button class="btn alt" data-action="finance">Finance transactions</button></div><div class="cards"><div class="card"><div class="head"><h3>Budget envelopes</h3><span class="muted">'+S.profile.currency+'</span></div>'+S.budgets.map(b=>'<div style="margin:16px 0"><div class="progress-text"><span>'+esc(b.title)+'</span><b>'+money(b.spent,S.profile.currency)+' / '+money(b.limit,S.profile.currency)+'</b></div><div class="progress"><i style="width:'+Math.min(100,b.spent/b.limit*100)+'%"></i></div></div>').join('')+'</div><div class="card"><div class="head"><h3>Installments · الأقساط</h3><button class="btn alt" data-action="addInstallment">+ Add</button></div>'+S.installments.map(x=>'<div class="row"><span><b>'+esc(x.title)+'</b><br><small class="muted">'+installmentLeft(x)+' payments · next '+installmentNext(x)+'</small></span><b>'+money(Math.max(0,x.total-x.paid),x.currency)+'</b></div>').join('')+(S.installments.length?'':'<div class="empty">Wala pa, add ka muna besh.</div>')+'</div></div>'+
 '<div class="card" style="margin-top:14px"><div class="head"><div><div class="eyebrow">FORECAST</div><h3>Forecast Next Month</h3></div><span class="pill orange">3-month average</span></div><div class="chart">'+['this','next'].map((x,i)=>'<div class="bar-group"><div class="bar-col bar-this" style="height:'+Math.max(5,Math.min(100,(i?pred.total:sumSpent())/Math.max(1,income)*100))+'%"></div><div class="bar-col bar-next" style="height:'+Math.max(5,Math.min(100,(i?pred.total:sumSpent())/Math.max(1,income)*100))+'%"></div></div>').join('')+'</div><div class="chart-legend"><span><i class="dot" style="background:#8FA8FF"></i> This month</span><span><i class="dot" style="background:#FF8A65"></i> Next prediction</span></div><div class="grid" style="margin-top:14px">'+pred.items.map(x=>'<div class="inner"><b>'+esc(x.title)+'</b><div class="progress-text"><span>Predicted</span><strong>'+money(x.pred,S.profile.currency)+'</strong></div><div class="progress"><i style="width:'+Math.min(100,x.pred/Math.max(1,x.limit)*100)+'%"></i></div></div>').join('')+'</div><div class="warning" style="margin-top:14px">Kung same gastos, <b>'+money(remain,S.profile.currency)+'</b> matitira next month. Tip: bawasan Grab Food by 20% = +₱1,200 ipon.</div></div>'))
}
function work(){
 const rec=S.clients.filter(c=>c.status!=='Paid').reduce((a,c)=>a+Number(c.amount||0),0),paid=S.clients.filter(c=>c.status==='Paid').reduce((a,c)=>a+Number(c.amount||0),0),over=S.clients.filter(c=>c.status==='Overdue').length;
 return shell('Clients & Invoices',section('WORK','Client & Invoice Mini-CRM','<div class="kpis"><div class="card kpi">Total receivable<strong>'+money(rec,S.profile.currency)+'</strong><span class="muted">Pending + overdue</span></div><div class="card kpi">Paid this month<strong>'+money(paid,S.profile.currency)+'</strong><span class="muted">Bayad na, galing!</span></div><div class="card kpi">Overdue<strong>'+over+'</strong><span class="muted">Siningil mo na ba? 😅</span></div><div class="card kpi">Clients<strong>'+S.clients.length+'</strong><span class="muted">All projects</span></div></div><div class="toolbar"><button class="btn" data-action="addClient">+ Add client</button><input id="clientSearch" placeholder="Search client, project..."><select id="clientStatus"><option>All</option><option>Pending</option><option>Paid</option><option>Overdue</option></select></div><div class="card table-wrap"><table class="table"><thead><tr><th>Client</th><th>Project</th><th>Rate</th><th>Status</th><th>Due</th><th>Days</th><th>Actions</th></tr></thead><tbody id="clientRows">'+clientRows()+'</tbody></table></div>'))
}
function clientRows(){let q=(document.getElementById('clientSearch')?.value||'').toLowerCase(),st=document.getElementById('clientStatus')?.value||'All';let a=S.clients.filter(c=>(c.name+' '+c.project).toLowerCase().includes(q)&&(st==='All'||c.status===st));return a.length?a.map(c=>'<tr><td><b>'+esc(c.name)+'</b><br><small>'+esc(c.notes||'')+'</small></td><td>'+esc(c.project)+'</td><td>'+money(c.amount,c.currency)+'</td><td><span class="status '+c.status.toLowerCase()+'">'+c.status+'</span></td><td>'+fmt(c.due)+'</td><td>'+days(c.due)+'</td><td><button class="btn alt" data-paid="'+c.id+'">Paid</button> <button class="btn alt" data-remind="'+c.id+'">Remind</button> <button class="btn alt" data-history="'+c.id+'">History</button></td></tr>').join(''):'<tr><td colspan="7"><div class="empty">Wala pa, add ka muna besh.</div></td></tr>'}
function lab(){return shell('Lab',section('NEW FEATURES','TUBAL HUB Lab','<div class="grid"><div class="card"><div class="head"><h3>⚡ Quick Capture</h3><span class="pill blue">Ctrl+K</span></div><p class="muted">Task, note, link, habit — type lang.</p><button class="btn" data-action="quick">Open Capture</button><div class="capture-list">'+S.captures.slice(-5).reverse().map(c=>'<div class="capture-item">'+esc(c.text)+'<small>'+esc(c.kind)+' · '+c.date+'</small></div>').join('')+'</div></div><div class="card"><div class="head"><h3>🕌 Prayer Conflict Guard</h3><span class="pill yellow">'+(S.settings.prayerGuard?'ON':'OFF')+'</span></div><p class="muted">Warns kapag tumatama ang event sa prayer + 15min buffer.</p><button class="btn alt" data-action="settings">Open settings</button></div><div class="card"><div class="head"><h3>📊 Budget Forecast</h3><span class="pill orange">3-month avg</span></div><p class="muted">Predicted spent + remaining next month.</p><button class="btn alt" data-route="budget">Open Budget</button></div><div class="card"><div class="head"><h3>🧾 Mini-CRM</h3><span class="pill green">REAL DATA</span></div><p class="muted">Clients, invoices, due dates, reminders.</p><button class="btn alt" data-route="work">Open CRM</button></div><div class="card close-card"><div class="head"><h3>🌙 Daily Closing</h3><span>'+journalStreak()+' days</span></div><p class="muted">9 PM ritual — 3 wins, top 3 bukas, mood.</p><button class="btn" style="background:#fff;color:#111" data-action="closing">Mag-close ng araw</button></div><div class="card"><div class="head"><h3>Backup</h3><span class="pill blue">JSON</span></div><p class="muted">Export/import lahat ng v2 data kasama ang new features.</p><button class="btn alt" data-action="export">Export All Data</button></div></div>'))
}
function forecast(){return {items:S.budgets.map(b=>{let base=Number(b.spent)||0;let vals=[base,base*.94,base*1.03];let pred=Math.round(vals.reduce((a,v)=>a+v,0)/3);return {...b,pred}}),get total(){return this.items.reduce((a,x)=>a+x.pred,0)}}}
function sumSpent(){return S.budgets.reduce((a,b)=>a+Number(b.spent||0),0)}
function installmentLeft(x){return Math.ceil(Math.max(0,x.total-x.paid)/Math.max(1,x.monthly))}
function installmentNext(x){let d=new Date(x.first+'T00:00:00');let paid=Math.floor(x.paid/Math.max(1,x.monthly));d.setMonth(d.getMonth()+paid);return iso(d)}
function nextPrayer(){let now=new Date(),list=[['Fajr',4,30],['Dhuhr',12,0],['Asr',15,30],['Maghrib',18,0],['Isha',19,15]];for(let p of list){let t=new Date(now);t.setHours(p[1],p[2],0,0);if(t>now)return {name:p[0],time:PRAYERS[p[0].toLowerCase()],remaining:remaining(t-now)}}let t=new Date(now);t.setDate(t.getDate()+1);t.setHours(4,30,0,0);return {name:'Fajr',time:PRAYERS.fajr,remaining:remaining(t-now)}}
function remaining(ms){let m=Math.max(0,Math.round(ms/60000));return Math.floor(m/60)+'h '+m%60+'m'}
function prayerConflict(date,time){if(!S.settings.prayerGuard||!time)return null;let [h,mi]=time.split(':').map(Number),mins=h*60+mi;let list=[['Fajr',270],['Dhuhr',720],['Asr',930],['Maghrib',1080],['Isha',1155]];for(const [name,p] of list)if(Math.abs(mins-p)<=15)return {name,time:PRAYERS[name.toLowerCase()],suggest:minutesToTime(p+30)};return null}
function minutesToTime(m){let h=Math.floor(m/60)%24,mi=String(m%60).padStart(2,'0');return String(h).padStart(2,'0')+':'+mi}
function heatmap(){let html='';for(let i=363;i>=0;i--){let d=iso(new Date(new Date(TODAY+'T00:00:00').getTime()-i*86400000)),n=S.habits.filter(h=>h.checks[d]).length,p=n/(S.habits.length||1);html+='<i class="heat '+(p>=1?'l4':p>=.66?'l3':p>=.33?'l2':p?'l1':'')+'"></i>'}return '<div class="heatmap">'+html+'</div>'}
function journalStreak(){let set=new Set(S.journals.map(j=>j.date)),n=0,d=new Date(TODAY+'T00:00:00');while(set.has(iso(d))){n++;d.setDate(d.getDate()-1)}return n}

function openModal(title,body,onSubmit){
 const root=document.getElementById('modalRoot');root.className='modal-root show';root.innerHTML='<div class="overlay" data-close><div class="dialog"><h2>'+title+'</h2><div class="dialog-sub">Kaya pa. Fill up lang, then Save.</div><form id="modalForm">'+body+'<div class="actions"><button type="button" class="btn alt" data-cancel>Cancel</button><button class="btn">Save</button></div></form></div></div>';
 root.querySelector('[data-cancel]').onclick=closeModal;root.querySelector('.overlay').onclick=e=>{if(e.target===e.currentTarget)closeModal()};root.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.target))}
}
function closeModal(){const r=document.getElementById('modalRoot');r.className='modal-root';r.innerHTML=''}
function taskModal(){openModal('Add Task','<div class="form-grid"><div class="field"><label>Task</label><input name="title" required placeholder="Ano ang gagawin?"></div><div class="field"><label>Date</label><input name="date" type="date" value="'+TODAY+'" required></div><div class="field"><label>Priority</label><select name="priority"><option>mid</option><option>high</option><option>low</option></select></div><div class="field"><label>Category</label><select name="category"><option>General</option><option>Finance</option><option>Work</option><option>Family</option></select></div><div class="field"><label>Recurring</label><select name="recurring"><option value="none">One-off</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></div></div>',f=>{S.tasks.unshift({id:uid(),title:f.get('title'),date:f.get('date'),priority:f.get('priority'),category:f.get('category'),project:'',done:false,recurring:f.get('recurring')});save();closeModal();render()})}
function eventModal(){
 openModal('Add Calendar Event','<div class="form-grid"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Date</label><input name="date" type="date" value="'+TODAY+'" required></div><div class="field"><label>Time</label><input name="time" type="time" required></div><div class="field"><label>Color</label><select name="color"><option value="blue">Blue</option><option value="orange">Orange</option><option value="green">Green</option><option value="pink">Pink</option></select></div></div><div id="prayerWarning"></div>',f=>{let c=prayerConflict(f.get('date'),f.get('time'));if(c&&!confirm('⚠️ Tatama sa '+c.name+' ('+c.time+') — i-reschedule sa '+c.suggest+'?\n\nOK = gamitin ang suggested time, Cancel = keep original')){return}let time=c?c.suggest:f.get('time');S.events.push({id:uid(),title:f.get('title'),date:f.get('date'),time,color:f.get('color')});save();closeModal();render()});
 const form=document.getElementById('modalForm'),warn=document.getElementById('prayerWarning');form.addEventListener('input',()=>{let d=form.date.value,t=form.time.value,c=prayerConflict(d,t);warn.innerHTML=c?'<div class="warning">⚠️ Tatama sa <b>'+c.name+' ('+c.time+')</b> — i-reschedule sa <b>'+c.suggest+'</b>?</div>':''})
}
function noteModal(prefill=''){
 openModal('Add Note','<div class="form-grid"><div class="field"><label>Type</label><select name="type"><option>Notes</option><option>Duas</option><option>Links</option><option>Places</option><option>Tips</option><option>Journal</option></select></div><div class="field"><label>Title</label><input name="title" value="'+esc(prefill?'Quick Note':'')+'" required></div><div class="field full"><label>Content</label><textarea name="content" rows="6" required>'+esc(prefill)+'</textarea></div><div class="field"><label>Tags</label><input name="tags" placeholder="work, idea"></div></div>',f=>{S.notes.unshift({id:uid(),type:f.get('type'),title:f.get('title'),content:f.get('content'),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean),pinned:false,date:TODAY});save();closeModal();render()})
}
function clientModal(){
 openModal('Add Client / Invoice','<div class="form-grid"><div class="field"><label>Client name</label><input name="name" required></div><div class="field"><label>Project</label><input name="project" required></div><div class="field"><label>Amount</label><input name="amount" type="number" required></div><div class="field"><label>Currency</label><select name="currency"><option>PHP</option><option>USD</option><option>EUR</option></select></div><div class="field"><label>Due date</label><input name="due" type="date" value="'+TODAY+'" required></div><div class="field"><label>Status</label><select name="status"><option>Pending</option><option>Paid</option><option>Overdue</option></select></div><div class="field full"><label>Notes</label><textarea name="notes" rows="3"></textarea></div></div>',f=>{let c={id:uid(),name:f.get('name'),project:f.get('project'),amount:+f.get('amount'),currency:f.get('currency'),due:f.get('due'),status:f.get('status'),notes:f.get('notes'),history:[{date:TODAY,event:'Created'}]};S.clients.unshift(c);S.finance.transactions.push({id:uid(),type:'receivable',clientId:c.id,amount:c.amount,currency:c.currency,date:TODAY,status:c.status});save();closeModal();render()})
}
function closingModal(){
 const already=S.journals.some(j=>j.date===TODAY);openModal('Kumusta araw mo? 🌙','<div class="field"><label>Ano natapos mo today? (3 wins)</label><textarea name="wins" rows="5" required placeholder="1. ...\n2. ...\n3. ..."></textarea></div><div class="field" style="margin-top:12px"><label>Top 3 bukas?</label><textarea name="tomorrow" rows="5" required placeholder="1. ...\n2. ...\n3. ..."></textarea></div><div class="field" style="margin-top:12px"><label>Mood</label><div class="mood"><label><input type="radio" name="mood" value="😊" checked> 😊</label><label><input type="radio" name="mood" value="😐"> 😐</label><label><input type="radio" name="mood" value="😓"> 😓</label><label><input type="radio" name="mood" value="🔥"> 🔥</label></div></div>'+(already?'<div class="warning">May closing note ka na today. Save ulit kung gusto mong palitan.</div>':''),f=>{S.journals=S.journals.filter(j=>j.date!==TODAY);S.journals.push({id:uid(),date:TODAY,wins:f.get('wins'),tomorrow:f.get('tomorrow'),mood:f.get('mood')});S.notes.unshift({id:uid(),type:'Journal',title:'Daily Closing · '+TODAY,content:'Wins:\n'+f.get('wins')+'\n\nTop 3 bukas:\n'+f.get('tomorrow'),tags:['journal'],pinned:false,date:TODAY});save();closeModal();render()})
}
function quickModal(){
 const root=document.getElementById('modalRoot');root.className='modal-root show';root.innerHTML='<div class="overlay" data-close><div class="dialog quick-dialog"><h2>Quick Capture</h2><div class="dialog-sub">Ano idadagdag? (task, note, link, habit)</div><input id="quickInput" autocomplete="off" placeholder="task: Bayaran PLDT bukas 5pm"><div class="quick-help"><span>task:</span><span>note:</span><span>link:</span><span>habit:</span></div><div class="capture-list">'+S.captures.slice(-5).reverse().map(c=>'<div class="capture-item">'+esc(c.text)+'<small>'+esc(c.kind)+' · '+c.date+'</small></div>').join('')+'</div><div class="actions"><button class="btn alt" data-cancel>Close</button><button class="btn" id="quickSave">Capture</button></div></div></div>';root.querySelector('[data-cancel]').onclick=closeModal;root.querySelector('.overlay').onclick=e=>{if(e.target===e.currentTarget)closeModal()};const input=document.getElementById('quickInput');input.focus();const submit=()=>{let text=input.value.trim();if(!text)return;capture(text);closeModal();render()};document.getElementById('quickSave').onclick=submit;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();submit()}if(e.key==='Escape')closeModal()}}
function capture(text){
 let lower=text.toLowerCase(),kind='smart';if(lower.startsWith('task:')){kind='task';S.tasks.unshift({id:uid(),title:text.slice(5).trim(),date:TODAY,priority:'mid',category:'General',project:'',done:false,recurring:'none'})}else if(lower.startsWith('note:')){kind='note';S.notes.unshift({id:uid(),type:'Notes',title:'Quick Note',content:text.slice(5).trim(),tags:['quick'],pinned:false,date:TODAY})}else if(lower.startsWith('link:')){kind='link';S.notes.unshift({id:uid(),type:'Links',title:'Saved Link',content:text.slice(5).trim(),tags:['link'],pinned:false,date:TODAY})}else if(lower.startsWith('habit:')){kind='habit';S.habits.unshift({id:uid(),title:text.slice(6).trim(),icon:'✨',checks:{}})}else if(lower.includes('http://')||lower.includes('https://')){kind='link';S.notes.unshift({id:uid(),type:'Links',title:'Saved Link',content:text,tags:['link'],pinned:false,date:TODAY})}else{kind='task';S.tasks.unshift({id:uid(),title:text,date:TODAY,priority:'mid',category:'General',project:'',done:false,recurring:'none'})}S.captures.push({id:uid(),text,kind,date:TODAY});S.captures=S.captures.slice(-30);save()
}
function bind(){
 document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
 document.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>{let t=S.tasks.find(x=>x.id==b.dataset.task);if(!t)return;t.done=b.checked;if(t.done&&t.recurring!=='none')repeatTask(t);save();render()});
 document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>{let c=S.clients.find(x=>x.id==b.dataset.paid);if(c){c.status='Paid';c.history.push({date:TODAY,event:'Marked paid'});save();render()}});
 document.querySelectorAll('[data-remind]').forEach(b=>b.onclick=()=>{let c=S.clients.find(x=>x.id==b.dataset.remind);if(c)navigator.clipboard?.writeText('Hi '+c.name+', gentle reminder lang po sa '+c.project+' invoice na '+money(c.amount,c.currency)+' due '+fmt(c.due)+'. Salamat!');alert('Reminder text copied.');});
 document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{let c=S.clients.find(x=>x.id==b.dataset.history);alert(c.name+' history:\n'+c.history.map(h=>h.date+' — '+h.event).join('\n'))});
 document.getElementById('clientSearch')?.addEventListener('input',()=>{let r=document.getElementById('clientRows');if(r)r.innerHTML=clientRows();bind()});
 document.getElementById('clientStatus')?.addEventListener('change',()=>{let r=document.getElementById('clientRows');if(r)r.innerHTML=clientRows();bind()});
}
function repeatTask(t){let d=new Date(t.date+'T00:00:00');if(t.recurring==='daily')d.setDate(d.getDate()+1);if(t.recurring==='weekly')d.setDate(d.getDate()+7);if(t.recurring==='monthly'){let n=d.getDate();d.setMonth(d.getMonth()+1);if(d.getDate()!==n)d.setDate(0)}S.tasks.push({...t,id:uid(),date:iso(d),done:false})}
function action(a){
 if(a==='quick')quickModal();else if(a==='closing')closingModal();else if(a==='addTask')taskModal();else if(a==='addEvent')eventModal();else if(a==='addClient')clientModal();else if(a==='addNote')noteModal();else if(a==='settings')settingsModal();else if(a==='export')exportData();else if(a==='import')document.getElementById('importInput').click();else if(a==='finance')financeModal();else if(a==='addBudget')budgetModal();else if(a==='addInstallment')installmentModal();else if(a==='addGoal')goalModal();else if(a==='addHabit')habitModal();else if(a==='addLibrary')libraryModal();else if(a==='addBirthday')birthdayModal();else if(a==='addProject')projectModal();else if(a==='addRenewal')renewalModal()
}
function settingsModal(){openModal('Settings','<div class="form-grid"><div class="field"><label>Name</label><input name="name" value="'+esc(S.profile.name)+'"></div><div class="field"><label>City</label><select name="city"><option '+(S.profile.city==='Davao City'?'selected':'')+'>Davao City</option><option '+(S.profile.city==='Quezon City'?'selected':'')+'>Quezon City</option></select></div><div class="field"><label>Currency</label><select name="currency"><option '+(S.profile.currency==='PHP'?'selected':'')+'>PHP</option><option>USD</option><option>EUR</option></select></div><div class="field"><label>Prayer Conflict Guard</label><select name="guard"><option value="on" '+(S.settings.prayerGuard?'selected':'')+'>Enabled</option><option value="off" '+(!S.settings.prayerGuard?'selected':'')+'>Disabled</option></select></div><div class="field full"><label>Daily Closing Ritual</label><select name="closing"><option value="on" '+(S.settings.closingEnabled?'selected':'')+'>Enabled · 9 PM</option><option value="off" '+(!S.settings.closingEnabled?'selected':'')+'>Disabled</option></select></div></div>',f=>{S.profile.name=f.get('name');S.profile.city=f.get('city');S.profile.currency=f.get('currency');S.settings.prayerGuard=f.get('guard')==='on';S.settings.closingEnabled=f.get('closing')==='on';save();closeModal();render()})}
function financeModal(){openModal('Finance Transaction','<div class="form-grid"><div class="field"><label>Type</label><select name="type"><option>payable</option><option>receivable</option></select></div><div class="field"><label>Amount</label><input name="amount" type="number" required></div><div class="field"><label>Currency</label><select name="currency"><option>PHP</option><option>USD</option></select></div><div class="field"><label>Date</label><input name="date" type="date" value="'+TODAY+'"></div></div>',f=>{S.finance.transactions.push({id:uid(),type:f.get('type'),amount:+f.get('amount'),currency:f.get('currency'),date:f.get('date'),status:'open'});save();closeModal();render()})}
function budgetModal(){openModal('Add Budget Envelope','<div class="form-grid"><div class="field"><label>Name</label><input name="title" required></div><div class="field"><label>Limit</label><input name="limit" type="number" required></div><div class="field"><label>Spent</label><input name="spent" type="number" value="0"></div></div>',f=>{S.budgets.push({title:f.get('title'),limit:+f.get('limit'),spent:+f.get('spent')});save();closeModal();render()})}
function installmentModal(){openModal('Add Installment · الأقساط','<div class="form-grid"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Currency</label><select name="currency"><option>PHP</option><option>USD</option></select></div><div class="field"><label>Total</label><input name="total" type="number" required></div><div class="field"><label>Monthly</label><input name="monthly" type="number" required></div><div class="field"><label>First due</label><input name="first" type="date" value="'+TODAY+'" required></div></div>',f=>{S.installments.push({id:uid(),title:f.get('title'),currency:f.get('currency'),total:+f.get('total'),monthly:+f.get('monthly'),first:f.get('first'),paid:0});save();closeModal();render()})}
function goalModal(){openModal('Add Goal','<div class="form-grid"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Category</label><select name="category"><option>Career</option><option>Money</option><option>Health</option><option>Family</option><option>Personal</option></select></div><div class="field full"><label>Target date</label><input name="date" type="date" required></div><div class="field full"><label>Subtasks, one per line</label><textarea name="subs" rows="5"></textarea></div></div>',f=>{S.goals.push({id:uid(),title:f.get('title'),category:f.get('category'),date:f.get('date'),subs:f.get('subs').split('\n').filter(Boolean).map(x=>[x,false])});save();closeModal();render()})}
function habitModal(){openModal('Add Habit','<div class="form-grid"><div class="field full"><label>Habit</label><input name="title" required placeholder="Halimbawa: Read 10 pages"></div><div class="field"><label>Icon</label><input name="icon" value="✨"></div></div>',f=>{S.habits.push({id:uid(),title:f.get('title'),icon:f.get('icon'),checks:{}});save();closeModal();render()})}
function libraryModal(){openModal('Add Library Item','<div class="form-grid"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Author</label><input name="author"></div><div class="field"><label>Type</label><select name="type"><option>Books</option><option>Courses</option></select></div><div class="field"><label>Status</label><select name="status"><option>Want to read</option><option>Reading</option><option>Finished</option></select></div></div>',f=>{S.library.push({id:uid(),title:f.get('title'),author:f.get('author'),type:f.get('type'),status:f.get('status'),rating:0,read:0,total:100});save();closeModal();render()})}
function birthdayModal(){openModal('Add Birthday','<div class="form-grid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>MM-DD</label><input name="date" placeholder="12-03" required></div><div class="field"><label>Emoji</label><input name="emoji" value="🎂"></div></div>',f=>{S.birthdays.push({id:uid(),name:f.get('name'),date:f.get('date'),emoji:f.get('emoji')});save();closeModal();render()})}
function projectModal(){openModal('Add Project','<div class="form-grid"><div class="field full"><label>Project title</label><input name="title" required></div><div class="field"><label>Expected tasks</label><input name="total" type="number" value="5"></div></div>',f=>{S.projects.push({id:uid(),title:f.get('title'),tasksTotal:+f.get('total')||5});save();closeModal();render()})}
function renewalModal(){openModal('Add Renewal','<div class="form-grid"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Type</label><input name="type" value="Subscription"></div><div class="field full"><label>Date</label><input name="date" type="date" required></div></div>',f=>{S.renewals.push({id:uid(),title:f.get('title'),type:f.get('type'),date:f.get('date')});save();closeModal();render()})}
function exportData(){let payload={version:2,exportedAt:new Date().toISOString(),...S};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='tubalhub-v2-backup-'+TODAY+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.getElementById('importInput').addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);delete x.version;delete x.exportedAt;S=Object.assign(structuredClone(seed),x);S.profile.setup=true;save();render();alert('Import successful. Ayos!')}catch{alert('Invalid JSON backup.')}};r.readAsText(f);e.target.value=''});

function onboarding(){
 document.getElementById('app').innerHTML='<div class="onboard"><div class="dialog"><div class="eyebrow">TUBAL HUB v2 · PERSONAL OS</div><h1>Welcome, Ar-ar Tubal 👋</h1><p class="muted">Set up once. Everything stays in your browser unless ikaw ang mag-export.</p><form id="setupForm" class="form"><div class="form-grid"><div class="field"><label>Name</label><input name="name" placeholder="Ar-ar Tubal" required></div><div class="field"><label>City</label><select name="city"><option>Davao City</option><option>Quezon City</option></select></div><div class="field"><label>Currency</label><select name="currency"><option>PHP</option><option>USD</option><option>EUR</option></select></div></div><div class="field"><label>Enable features</label><div class="feature-checks"><label class="feature-check"><input type="checkbox" name="prayer" checked> 🕌 Prayer Conflict Guard</label><label class="feature-check"><input type="checkbox" name="budget" checked> 📊 Budget Forecast</label><label class="feature-check"><input type="checkbox" name="quick" checked> ⚡ Quick Capture</label><label class="feature-check"><input type="checkbox" name="crm" checked> 🧾 Client & Invoice CRM</label><label class="feature-check"><input type="checkbox" name="closing" checked> 🌙 Daily Closing Ritual</label></div></div><button class="btn">Start TUBAL HUB v2 →</button></form></div></div>';
 document.getElementById('setupForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);S.profile={...S.profile,name:f.get('name'),city:f.get('city'),currency:f.get('currency'),setup:true,prayerGuard:f.get('prayer')==='on'};S.settings.prayerGuard=f.get('prayer')==='on';S.settings.closingEnabled=f.get('closing')==='on';save();go('home')}
}
function render(){
 if(!S.profile.setup){onboarding();return}
 let body={home,lifehub,calendar,budget,work,lab}[route]||home;
 document.getElementById('app').innerHTML=body();
 bind();
}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();quickModal()}if(e.key==='Escape')closeModal()});
function maybeClosing(){if(!S.profile.setup||!S.settings.closingEnabled)return;let h=new Date().getHours();if(h>=21&&!S.journals.some(j=>j.date===TODAY))setTimeout(closingModal,500)}
setInterval(()=>maybeClosing(),3600000);
render();setTimeout(maybeClosing,700);

/* ========================= TUBAL HUB v3 EXTENSION ========================= */
const V3={focusKey:'tubalhub_focus_sessions',vaultKey:'tubalhub_vault_v2',reviewsKey:'tubalhub_weekly_reviews',changelogKey:'tubalhub_changelog',searchKey:'tubalhub_recent_searches',themeKey:'tubalhub_dark_mode'};
function migrateV3(){
 try{
  if(!localStorage.getItem(V3.changelogKey))localStorage.setItem(V3.changelogKey,JSON.stringify([
   {id:uid(),version:'v3.0',date:'2026-09-27',title:'Focus Mode + Pomodoro',description:'Fullscreen focus timer with sessions and Deep Work streak.',type:'Feature'},
   {id:uid(),version:'v3.0',date:'2026-09-27',title:'Secure Vault v2 with real encryption',description:'AES-GCM 256 vault with PBKDF2 master key derivation and auto-lock.',type:'Feature'},
   {id:uid(),version:'v3.0',date:'2026-09-27',title:'Command Palette v2',description:'Search, commands and quick add in one Ctrl+K palette.',type:'Improvement'},
   {id:uid(),version:'v3.0',date:'2026-09-27',title:'Weekly Review + Image export',description:'Automatic weekly summary with copy and PNG export.',type:'Feature'},
   {id:uid(),version:'v2.0',date:'2026-09-01',title:'Prayer Guard, Budget Forecast, Quick Capture, Client CRM, Closing Ritual',description:'Five core Personal OS features.',type:'Feature'},
   {id:uid(),version:'v1.0',date:'2026-08-01',title:'Initial LifeHub launch',description:'Personal organizer foundation.',type:'Feature'}
  ]));
  S.focus=S.focus||{prefs:{minutes:25,sound:true}};S.settings=S.settings||{closingEnabled:true,prayerGuard:true};save();
 }catch(e){console.warn('v3 migration',e)}
}
function v3LoadArray(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}
function v3SaveArray(k,a){localStorage.setItem(k,JSON.stringify(a))}
function focusSessions(){return v3LoadArray(V3.focusKey)}
function focusToday(){return focusSessions().filter(x=>x.date===TODAY)}
function focusMinutesToday(){return focusToday().reduce((a,x)=>a+(x.duration||0),0)}
function focusCountToday(){return focusToday().length}
function focusDeepStreak(){let n=0,d=new Date(TODAY+'T00:00:00'),set=new Set(focusSessions().map(x=>x.date));while(set.has(iso(d))){n++;d.setDate(d.getDate()-1)}return n}
function beep(){try{if(!S.focus.prefs.sound)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ac=new C(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=880;g.gain.value=.06;o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.18);setTimeout(()=>ac.close(),400)}catch{}}
let focusTimer=null,focusState=null,focusRemaining=1500,focusEndAt=0,focusPaused=true,focusPomodoros=0;
function startFocus(taskId){const t=S.tasks.find(x=>x.id==taskId)||S.tasks.find(x=>!x.done)||S.tasks[0];if(!t)return;focusState={task:t,mode:'work',duration:(S.focus.prefs.minutes||25)*60};focusRemaining=focusState.duration;focusEndAt=Date.now()+focusRemaining*1000;focusPaused=false;focusPomodoros=0;renderFocus();clearInterval(focusTimer);focusTimer=setInterval(()=>{if(focusPaused)return;focusRemaining=Math.max(0,Math.ceil((focusEndAt-Date.now())/1000));updateFocusUI();if(!focusRemaining)finishFocusPhase()},250)}
function finishFocusPhase(){beep();if(focusState.mode==='work'){const mins=Math.round(focusState.duration/60),a=focusSessions();a.push({id:uid(),date:TODAY,task:focusState.task.title,taskId:focusState.task.id,duration:mins,type:'work',createdAt:new Date().toISOString()});v3SaveArray(V3.focusKey,a);focusState.task.pomodoros=(focusState.task.pomodoros||0)+1;let h=S.habits.find(x=>x.title==='Deep Work');if(!h){h={id:uid(),title:'Deep Work',icon:'🎯',checks:{}};S.habits.push(h)}h.checks[TODAY]=(h.checks[TODAY]||0)+1;save();focusPomodoros++;focusState.mode='break';focusState.duration=(focusPomodoros%4===0?15:5)*60}else{focusState.mode='work';focusState.duration=(S.focus.prefs.minutes||25)*60}focusRemaining=focusState.duration;focusEndAt=Date.now()+focusRemaining*1000;focusPaused=false;renderFocus()}
function focusClock(){return String(Math.floor(focusRemaining/60)).padStart(2,'0')+':'+String(focusRemaining%60).padStart(2,'0')}
function focusProgress(){return Math.max(0,Math.min(100,(1-focusRemaining/(focusState?.duration||1500))*100))}
function renderFocus(){const root=document.getElementById('modalRoot');root.className='modal-root show focus-root';const t=focusState.task;root.innerHTML='<div class="focus-screen"><div class="focus-top"><span>'+focusCountToday()+' pomodoros today · '+Math.floor(focusMinutesToday()/60)+'h '+focusMinutesToday()%60+'m focused</span><button class="focus-exit" id="focusExit">ESC · Exit</button></div><div class="focus-center"><div class="focus-kicker">'+(focusState.mode==='work'?'FOCUS':'BREAK')+'</div><h1>Naka-focus ka sa:<br><b>'+esc(t.title)+'</b></h1><div class="focus-ring" style="--p:'+focusProgress()+'%"><div class="focus-time">'+focusClock()+'</div></div><div class="focus-controls"><button class="focus-btn" id="focusPause">'+(focusPaused?'Resume':'Pause')+'</button><button class="focus-btn" id="focusReset">Reset</button><button class="focus-btn" id="focusSkip">Skip</button></div><p class="focus-note">'+(focusState.mode==='work'?'One task lang. Kaya mo yan.':'Break muna. Tubig, stretch, balik.')+'</p></div></div>';document.getElementById('focusExit').onclick=closeFocus;document.getElementById('focusPause').onclick=()=>{focusPaused=!focusPaused;if(!focusPaused)focusEndAt=Date.now()+focusRemaining*1000;updateFocusUI()};document.getElementById('focusReset').onclick=()=>{focusRemaining=focusState.duration;focusEndAt=Date.now()+focusRemaining*1000;focusPaused=false;updateFocusUI()};document.getElementById('focusSkip').onclick=()=>{focusRemaining=0;finishFocusPhase()}}
function updateFocusUI(){document.querySelector('.focus-time')?.replaceChildren(document.createTextNode(focusClock()));document.querySelector('.focus-ring')?.style.setProperty('--p',focusProgress()+'%');const b=document.getElementById('focusPause');if(b)b.textContent=focusPaused?'Resume':'Pause'}
function closeFocus(){clearInterval(focusTimer);focusState=null;focusPaused=true;closeModal();render()}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&focusState)closeFocus()});

async function deriveVaultKey(password,salt){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf)))}function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function vaultEncrypt(obj,key){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(obj)));return{iv:b64(iv),data:b64(ct)}}
async function vaultDecrypt(item,key){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(item.iv)},key,unb64(item.data));return JSON.parse(new TextDecoder().decode(pt))}
let vaultKey=null,vaultLockTimer=null;
function vaultMeta(){try{return JSON.parse(localStorage.getItem(V3.vaultKey)||'null')}catch{return null}}
function vaultTouch(){clearTimeout(vaultLockTimer);if(vaultKey)vaultLockTimer=setTimeout(()=>{vaultKey=null;render()},300000)}
function recoveryWords(){return 'amber river candle orbit mango quiet cedar velvet sunrise copper meadow lantern'.split(' ')}
function downloadBlob(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function setupVault(password){const salt=crypto.getRandomValues(new Uint8Array(16));vaultKey=await deriveVaultKey(password,salt);const meta={version:2,salt:b64(salt),items:[],recovery:recoveryWords(),createdAt:new Date().toISOString()};localStorage.setItem(V3.vaultKey,JSON.stringify(meta));vaultTouch()}
async function unlockVault(password){const meta=vaultMeta();if(!meta)return false;try{const key=await deriveVaultKey(password,unb64(meta.salt));if(meta.items?.length)await vaultDecrypt(meta.items[0],key);vaultKey=key;vaultTouch();return true}catch{vaultKey=null;return false}}
async function vaultItems(){const meta=vaultMeta();if(!meta||!vaultKey)return[];const out=[];for(const x of meta.items||[]){try{out.push({...await vaultDecrypt(x,vaultKey),_id:x.id})}catch{}}vaultTouch();return out}
async function saveVaultItem(obj){const meta=vaultMeta();if(!meta||!vaultKey)throw Error('Locked');const enc=await vaultEncrypt(obj,vaultKey);meta.items.push({id:uid(),...enc});localStorage.setItem(V3.vaultKey,JSON.stringify(meta));vaultTouch()}
function vaultSetupModal(){openModal('Secure Vault v2','<div class="warning">Master password mo lang nakaka-decrypt nito — wag mo makalimutan besh!</div><div class="field"><label>Master password · minimum 8 chars</label><input name="password" type="password" minlength="8" required></div><div class="field" style="margin-top:12px"><label>12-word recovery key</label><div class="recovery-box">'+recoveryWords().join(' ')+'</div><small class="muted">Isulat/simpan offline. Hindi nito bina-bypass ang AES encryption.</small></div>',async f=>{if(f.get('password').length<8)return alert('Minimum 8 characters.');await setupVault(f.get('password'));closeModal();render()})}
function vaultUnlockModal(){openModal('Unlock Secure Vault','<div class="warning">Auto-lock: 5 minutes inactivity.</div><div class="field"><label>Master password</label><input name="password" type="password" required></div>',async f=>{if(await unlockVault(f.get('password'))){closeModal();render()}else alert('Wrong master password.')})}
function addVaultItemModal(){openModal('Add Secure Item','<div class="form-grid"><div class="field"><label>Type</label><select name="type"><option>Password</option><option>Card</option><option>ID</option><option>Note</option></select></div><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Username / ID</label><input name="username"></div><div class="field"><label>Password / Number</label><input name="secret" type="password"></div><div class="field full"><label>Tags</label><input name="tags"></div></div>',async f=>{await saveVaultItem({type:f.get('type'),title:f.get('title'),username:f.get('username'),secret:f.get('secret'),tags:f.get('tags'),createdAt:new Date().toISOString()});closeModal();render()})}
async function vaultModal(){if(!vaultMeta())return vaultSetupModal();if(!vaultKey)return vaultUnlockModal();addVaultItemModal()}
async function vaultPage(){const meta=vaultMeta(),items=vaultKey?await vaultItems():[];return shell('Secure Vault',section('PRIVATE','Secure Vault v2','<div class="warning">🔐 Master password mo lang nakaka-decrypt nito — wag mo makalimutan besh!</div><div class="toolbar"><button class="btn" data-action="vault">'+(meta?(vaultKey?'Lock / Add':'Unlock'):'Setup Vault')+'</button>'+(vaultKey?'<button class="btn alt" data-action="vaultAdd">+ Add item</button>':'')+'<button class="btn alt" data-action="vaultBackup">Download encrypted backup</button></div>'+(meta&&!vaultKey?'<div class="card"><h3>Vault Locked</h3><p class="muted">Unlock muna para makita ang encrypted items.</p></div>':'')+(items.length?'<div class="grid">'+items.map(x=>'<div class="card"><div class="head"><h3>'+esc(x.title)+'</h3><span class="pill blue">'+esc(x.type)+'</span></div><p>'+vaultMask(x)+'</p><button class="btn alt" data-reveal="'+x._id+'">👁 Reveal</button></div>').join(''):'<div class="empty">Wala pa, add ka muna besh.</div>'))}
function vaultMask(x){if(x.type==='Card'&&x.secret)return'•••• •••• •••• '+esc(String(x.secret).slice(-4));if(x.type==='ID')return'•••••••• '+esc(String(x.secret||'').slice(-4));return'••••••••••••'}
async function revealVault(id){if(!vaultKey)return vaultUnlockModal();const x=(await vaultItems()).find(i=>String(i._id)===String(id));if(x){vaultTouch();alert((x.username?'Username: '+x.username+'\\n':'')+(x.secret?'Secret: '+x.secret+'\\n':'')+(x.tags?'Tags: '+x.tags:''))}}
function vaultBackup(){const meta=vaultMeta();if(!meta)return alert('Setup Vault muna.');downloadBlob('tubalhub-vault-encrypted-backup.json',JSON.stringify(meta,null,2))}
function lockVault(){vaultKey=null;clearTimeout(vaultLockTimer);render()}

function fuzzyScore(q,s){q=q.toLowerCase().replace(/\\s+/g,'');s=s.toLowerCase();let i=0,score=0;for(const ch of q){let p=s.indexOf(ch,i);if(p<0)return-1;score+=p===i?3:1;i=p+1}return score}
function searchAll(q){const out=[],add=(type,icon,title,preview,route)=>{let sc=fuzzyScore(q,title+' '+preview);if(sc>=0)out.push({type,icon,title,preview,route,score:sc})};S.tasks.forEach(x=>add('Task','✓',x.title,(x.done?'Done':'Open')+' · '+x.date,'lifehub'));S.notes.forEach(x=>add(x.type,'✎',x.title,x.content,'lifehub'));S.clients.forEach(x=>add('Client','▤',x.name,x.project+' · '+money(x.amount,x.currency),'work'));S.goals.forEach(x=>add('Goal','◎',x.title,x.category,'lifehub'));S.library.forEach(x=>add(x.type||'Book','▣',x.title,x.author||x.status,'lifehub'));S.journals.forEach(x=>add('Journal','☾',x.date,x.wins,'home'));return out.sort((a,b)=>b.score-a.score).slice(0,12)}
function commands(){return[['budget','Jump to Budget','budget'],['savings','Add ₱500 sa Ipon envelope','add500'],['done','Mark all today done','done'],['focus','Start focus on top task','focusTop'],['export','Export data','export'],['dark','Toggle dark mode','dark'],['vault','Lock vault','lockVault']]}
function commandPalette(){const root=document.getElementById('modalRoot');root.className='modal-root show';root.innerHTML='<div class="overlay"><div class="dialog palette"><div class="palette-tabs"><button class="active" data-tab="search">Search</button><button data-tab="commands">Commands</button><button data-tab="add">Add</button></div><input id="paletteInput" autocomplete="off" placeholder="Search anything or type a command…"><div id="paletteResults"></div><div class="muted" style="margin-top:10px">↑ ↓ navigate · Enter select · Esc close</div></div></div>';const input=document.getElementById('paletteInput'),res=document.getElementById('paletteResults');let tab='search',idx=0;const data=()=>tab==='search'?searchAll(input.value.trim()):tab==='commands'?commands().map(x=>({icon:'⌘',title:x[1],preview:x[0],cmd:x[2]})):['task:','note:','link:','habit:'].map(x=>({icon:'+',title:x+' Quick Capture',preview:'Add item',cmd:x}));function draw(){let d=data();if(tab==='search'&&!input.value.trim())d=v3LoadArray(V3.searchKey).slice(-5).reverse().map(x=>({icon:'↺',title:x,preview:'Recent search',cmd:'recent'}));res.innerHTML=d.length?d.map((x,i)=>'<button class="palette-item '+(i===idx?'sel':'')+'" data-i="'+i+'"><b>'+x.icon+'</b><span><strong>'+highlight(x.title,input.value.trim())+'</strong><small>'+highlight(x.preview||'',input.value.trim())+'</small></span></button>').join(''):'<div class="empty">Wala nakita. Try another search.</div>';res.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>select(d[+b.dataset.i]))}function select(x){if(!x)return;if(tab==='search'){if(x.route)go(x.route);let q=input.value.trim();if(q){let a=v3LoadArray(V3.searchKey).filter(v=>v!==q);a.push(q);v3SaveArray(V3.searchKey,a.slice(-5))}closeModal();return}if(x.cmd==='add500'){let b=S.budgets.find(x=>x.title.toLowerCase()==='ipon');if(!b){b={title:'Ipon',spent:0,limit:5000};S.budgets.push(b)}b.spent+=500;save();closeModal();render()}else if(x.cmd==='done'){S.tasks.filter(t=>t.date===TODAY).forEach(t=>t.done=true);save();closeModal();render()}else if(x.cmd==='focusTop'){let t=S.tasks.find(t=>!t.done&&t.date===TODAY)||S.tasks.find(t=>!t.done);closeModal();if(t)startFocus(t.id)}else if(x.cmd==='export'){closeModal();exportData()}else if(x.cmd==='dark'){toggleDark();draw()}else if(x.cmd==='lockVault'){closeModal();lockVault()}else if(x.cmd==='budget'){closeModal();go('budget')}}input.oninput=()=>{idx=0;draw()};input.onkeydown=e=>{let d=data();if(e.key==='ArrowDown'){e.preventDefault();idx=Math.min(idx+1,d.length-1);draw()}else if(e.key==='ArrowUp'){e.preventDefault();idx=Math.max(0,idx-1);draw()}else if(e.key==='Enter'){e.preventDefault();select(d[idx])}else if(e.key==='Escape')closeModal()};root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;idx=0;root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));draw();input.focus()});draw();input.focus()}
function highlight(t,q){if(!q)return esc(t);return esc(t).replace(new RegExp('('+q.replace(/[.*+?^()|[\\]\\\\]/g,'\\\\$&')+')','ig'),'<mark>$1</mark>')}
function toggleDark(){document.body.classList.toggle('dark');localStorage.setItem(V3.themeKey,document.body.classList.contains('dark')?'1':'0')}
function weekRange(){let d=new Date(TODAY+'T00:00:00'),day=d.getDay(),start=new Date(d);start.setDate(d.getDate()-(day===0?6:day-1));let end=new Date(start);end.setDate(start.getDate()+6);return{start:iso(start),end:iso(end)}}
function weeklyReview(){const r=weekRange(),tasks=S.tasks.filter(t=>t.date>=r.start&&t.date<=r.end),done=tasks.filter(t=>t.done),fs=focusSessions().filter(x=>x.date>=r.start&&x.date<=r.end),journals=S.journals.filter(j=>j.date>=r.start&&j.date<=r.end),collected=S.clients.filter(c=>c.status==='Paid').reduce((a,c)=>a+Number(c.amount||0),0),pending=S.clients.filter(c=>c.status!=='Paid').reduce((a,c)=>a+Number(c.amount||0),0),env=S.budgets.map(b=>({title:b.title,spent:Number(b.spent)||0}));return{start:r.start,end:r.end,tasks,done,fs,journals,collected,pending,env,pomodoros:fs.length,focusMinutes:fs.reduce((a,x)=>a+x.duration,0),summary:'Ang sipag mo this week! '+done.length+' tasks done, pero keep an eye sa Food at other envelopes.'}}
function weeklyModal(){const r=weeklyReview();openModal('Weekly Review · '+r.start+' → '+r.end,'<div class="grid4"><div class="inner"><small>Tasks done</small><h2>'+r.done.length+'</h2></div><div class="inner"><small>Pomodoros</small><h2>'+r.pomodoros+'</h2></div><div class="inner"><small>Focused</small><h2>'+Math.floor(r.focusMinutes/60)+'h '+r.focusMinutes%60+'m</h2></div><div class="inner"><small>Collected</small><h2>'+money(r.collected,S.profile.currency)+'</h2></div></div><div class="cards" style="margin-top:12px"><div class="inner"><h3>Top completed</h3>'+r.done.slice(0,3).map(t=>'<div class="row">'+esc(t.title)+'</div>').join('')+'</div><div class="inner"><h3>Finance</h3>'+r.env.map(e=>'<div class="row"><span>'+esc(e.title)+'</span><b>'+money(e.spent,S.profile.currency)+'</b></div>').join('')+'</div></div><div class="inner" style="margin-top:12px"><b>'+esc(r.summary)+'</b><p class="muted">'+r.journals.length+' journal entries · '+S.clients.length+' clients total.</p></div>',f=>{let a=v3LoadArray(V3.reviewsKey);a.push({...r,createdAt:new Date().toISOString()});v3SaveArray(V3.reviewsKey,a);S.notes.unshift({id:uid(),type:'Weekly Review',title:'Weekly Review · '+r.start+' → '+r.end,content:r.summary,tags:['weekly'],pinned:false,date:TODAY});save();closeModal();render()})}
function copyWeekly(){const r=weeklyReview();navigator.clipboard?.writeText(r.summary+'\\nTasks: '+r.done.length+' done\\nPomodoros: '+r.pomodoros+'\\nCollected: '+money(r.collected,S.profile.currency));alert('Weekly review copied.')}
function shareWeeklyImage(){const r=weeklyReview(),cv=document.createElement('canvas');cv.width=1080;cv.height=1350;const x=cv.getContext('2d');x.fillStyle='#FCF9F5';x.fillRect(0,0,1080,1350);x.fillStyle='#1E1B16';x.font='800 52px Inter, sans-serif';x.fillText('TUBAL HUB',70,100);x.font='800 40px Inter, sans-serif';x.fillText('Weekly Review',70,170);x.font='500 25px Inter, sans-serif';x.fillText(r.start+' → '+r.end,70,215);x.font='800 78px Inter, sans-serif';x.fillText(String(r.done.length),70,340);x.font='500 26px Inter, sans-serif';x.fillText('tasks done',75,380);x.font='800 78px Inter, sans-serif';x.fillText(String(r.pomodoros),380,340);x.font='500 26px Inter, sans-serif';x.fillText('pomodoros',385,380);x.font='800 60px Inter, sans-serif';x.fillText(money(r.collected,S.profile.currency),70,500);x.font='500 25px Inter, sans-serif';x.fillText('collected',75,540);x.font='600 30px Inter, sans-serif';x.fillText('Ang sipag mo this week. Kaya pa!',70,650);x.font='500 25px Inter, sans-serif';x.fillText('TUBAL HUB by Ar-ar Tubal',70,1260);cv.toBlob(blob=>{if(blob)downloadBlob('tubalhub-weekly-review.png',blob,'image/png')},'image/png')}
function weeklyPage(){const a=v3LoadArray(V3.reviewsKey);return shell('Weekly Review',section('REFLECT','Weekly Review','<div class="hero"><div><div class="eyebrow">SUNDAY RITUAL</div><h2>Review, then reset.</h2><p>Generate your last 7 days. Walang judgment — facts lang, then next move.</p></div><button class="btn" data-action="weekly">Generate Weekly Review</button></div><div class="grid"><div class="card"><h3>Latest review</h3>'+(a.length?'<p>'+esc(a[a.length-1].summary)+'</p><small class="muted">'+a[a.length-1].start+' → '+a[a.length-1].end+'</small>':'<div class="empty">Wala pang review.</div>')+'</div><div class="card"><h3>Actions</h3><div class="toolbar"><button class="btn alt" data-action="weeklyCopy">Copy summary</button><button class="btn alt" data-action="weeklyImage">Share as image</button></div></div></div><div class="card" style="margin-top:14px">'+(a.length?a.slice().reverse().map(x=>'<div class="row"><span><b>'+x.start+' → '+x.end+'</b><br><small>'+esc(x.summary)+'</small></span><span class="pill blue">'+x.done.length+' done</span></div>').join(''):'<div class="empty">Wala pa, generate ka muna besh.</div>')+'</div>'))}
function changelogData(){return v3LoadArray(V3.changelogKey)}
function changelogPage(){const a=changelogData(),fresh=a.some(x=>days(x.date)>=0&&days(x.date)<7);return shell('Changelog',section('WHAT’S NEW','Ano bago sa Tubal Hub?','<div class="toolbar"><button class="btn" data-action="addChangelog">+ Add entry</button><button class="btn alt" data-action="exportChangelog">Export Markdown</button><span class="pill '+(fresh?'green':'blue')+'">'+(fresh?'What’s new':'Up to date')+'</span></div><div class="timeline">'+a.map(x=>'<article class="timeline-item"><div class="timeline-dot"></div><div class="card"><div class="head"><span class="pill '+(x.type==='Fix'?'green':x.type==='Improvement'?'blue':'orange')+'">'+esc(x.type)+'</span><small class="muted">'+esc(x.version)+' · '+fmt(x.date)+'</small></div><h3>'+esc(x.title)+'</h3><p class="muted">'+esc(x.description)+'</p></div></article>').join('')+'</div>'))}
function changelogModal(){let a=changelogData(),latest=a[0]?.version||'v3.0';openModal('Add Changelog Entry','<div class="form-grid"><div class="field"><label>Version</label><input name="version" value="'+esc(latest)+'"></div><div class="field"><label>Type</label><select name="type"><option>Feature</option><option>Fix</option><option>Improvement</option></select></div><div class="field full"><label>Title</label><input name="title" required></div><div class="field full"><label>Description</label><textarea name="description" rows="4" required></textarea></div></div>',f=>{a.unshift({id:uid(),version:f.get('version'),date:TODAY,title:f.get('title'),description:f.get('description'),type:f.get('type')});v3SaveArray(V3.changelogKey,a);closeModal();render()})}
function exportChangelog(){let md=changelogData().map(x=>'## '+x.version+' — '+x.title+'\\n**'+x.type+'** · '+x.date+'\\n\\n'+x.description).join('\\n\\n---\\n\\n');downloadBlob('CHANGELOG.md',md,'text/markdown')}
function v3HomeWidgets(){const today=focusToday(),vault=vaultMeta(),sun=new Date().getDay()===0,review=v3LoadArray(V3.reviewsKey);return'<div class="grid" style="margin-top:14px"><div class="card"><div class="head"><h3>🎯 Focus today</h3><span class="pill blue">'+today.length+' pomodoros</span></div><h2>'+Math.floor(focusMinutesToday()/60)+'h '+focusMinutesToday()%60+'m</h2><p class="muted">Deep Work streak: '+focusDeepStreak()+' days</p><button class="btn alt" data-action="focusTop">Start Focus</button></div><div class="card"><div class="head"><h3>🔐 Vault</h3><span class="pill '+(vaultKey?'green':'yellow')+'">'+(vault?(vaultKey?'UNLOCKED':'LOCKED'):'NOT SET')+'</span></div><p class="muted">'+(vault?'AES-GCM 256 · auto-lock 5 min':'Set up Secure Vault v2')+'</p><button class="btn alt" data-route="vault">Open Vault</button></div><div class="card"><div class="head"><h3>📋 Weekly Review</h3><span class="pill '+(sun?'orange':'blue')+'">'+(sun?'Sunday':'Any day')+'</span></div><p class="muted">'+(review.length?'Latest: '+review[review.length-1].start+' → '+review[review.length-1].end:'Generate your first review.')+'</p><button class="btn alt" data-action="weekly">Generate Review</button></div></div>'}
const oldHome=home,oldSidebar=sidebar,oldAction=action,oldBind=bind;
function home(){return oldHome()+v3HomeWidgets()}
function sidebar(){let base=oldSidebar();return base.replace('<div class="nav-section">Tools</div>','<div class="nav-section">V3</div><button class="'+(route==='vault'?'active':'')+'" data-route="vault">🔐 &nbsp; Vault</button><button class="'+(route==='weekly'?'active':'')+'" data-route="weekly">📋 &nbsp; Weekly Review</button><button class="'+(route==='changelog'?'active':'')+'" data-route="changelog">✦ &nbsp; Changelog</button><div class="nav-section">Tools</div>')}
function action(a){if(a==='focusTop'){let t=S.tasks.find(t=>!t.done&&t.date===TODAY)||S.tasks.find(t=>!t.done);if(t)startFocus(t.id)}else if(a==='vault')vaultModal();else if(a==='vaultAdd')addVaultItemModal();else if(a==='vaultBackup')vaultBackup();else if(a==='weekly')weeklyModal();else if(a==='weeklyCopy')copyWeekly();else if(a==='weeklyImage')shareWeeklyImage();else if(a==='addChangelog')changelogModal();else if(a==='exportChangelog')exportChangelog();else oldAction(a)}
function bind(){oldBind();document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>startFocus(b.dataset.focus));document.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>revealVault(b.dataset.reveal));document.getElementById('mobileMenu')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('open'))}
function render(){if(!S.profile.setup){onboarding();return}let body={home,lifehub,calendar,budget,work,lab,vault:vaultPage,weekly:weeklyPage,changelog:changelogPage}[route]||home;let result=body();if(result&&typeof result.then==='function')result.then(html=>{document.getElementById('app').innerHTML=html;bind()});else{document.getElementById('app').innerHTML=result;bind()}}
function exportData(){let payload={version:3,exportedAt:new Date().toISOString(),...S,v3:{focusSessions:focusSessions(),weeklyReviews:v3LoadArray(V3.reviewsKey),changelog:changelogData(),vault:'encrypted-separate-backup'}};downloadBlob('tubalhub-v3-backup-'+TODAY+'.json',JSON.stringify(payload,null,2))}
function quickModal(){commandPalette()}
document.body.classList.toggle('dark',localStorage.getItem(V3.themeKey)==='1');
